### ISSUE TITLE
Review delete bug submitted by Nico

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1003]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata content developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       confirm delete behavior
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>keep OneStop up to date</td>
  </tr>
</table>

## Tasks
- [ ] Confirm granule deletes working on Sciapps and/or Fed dev tier

**Comment by dneufeldcu** [comment]
Tested by Zeb on 9/19/19 against 2.3-snapshot. Moving to review, await confirmation from Nico before closing and once 2.3 is running on dev/test tiers.

**Comment by Ghebrechristos** [comment]
Granule delete can be sent via /registry/metadata/granule/{source}/UUID.
