### ISSUE TITLE
Fix `geoportal-search`

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#1004]
We need a common understanding of the technical implementation details of what we are providing with the geoportal-search WAR. At some point we lost context of what modifications needed to be made to their [v2.5.1 WAR zip](https://github.com/Esri/geoportal-server-catalog/releases/download/v2.5.1/geoportal-search-2.5.1.zip).

The latest containerized version we create of this WAR seems to try to unpack the default WAR provided by Esri, and do a string replacement in a `Config.js` file to change an Elasticsearch host, but inspecting the actual contents of that file, it appears this would have no effect on replacing any strings (did this product change underneath us?).

The other modification was we seemed to be trying to copy some `conf/WEB-INF` to the the default tomcat `WEB-INF` in the webapps directory, but I have been unable to find or reproduce this `conf` directory so it seems that copying from it would have no affect as well.

What are the criteria for successfully containerizing `geoportal-search` for OneStop's elasticsearch, as the modifications needed to do so seems like they may have changed.

**Comment by dneufeldcu** [comment]
We can drop support for geoportal-search from our devops perspective. If needed this issue can re-emerge if requested by our partner.
