### ISSUE TITLE
Where are the test data HazardImages granule thumbnails?

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#1010]
Our HazardImages test data (`onestop-test-data` repo) doesn’t contain thumbnails for granules, so we only see maps…could be a bug, but I see images on data.noaa.gov

This is independent of the fact that the Cart component always displays a Map component, regardless (which will be fixed in #995).

I have confirmed that there’s no `MD_BrowseGraphic` to be found in the granule XMLs under our test HazardImages directory, but there are for collections.

Comparing collections hosted on `data.noaa.gov`, we do not see this same issue, in general.

**Comment by amilan17** [comment]
@forgo  -- the metadata team has recently produced granules with MD_BrowseGraphic files for Hazard Images if you need them for testing. They are currently indexed on prod.

**Comment by dneufeldcu** [comment]
The have been requested, Nico to provide tar ball or equivalent.

**Comment by dneufeldcu** [comment]
Tarball forwarded via email to zeb, elliott
