### ISSUE TITLE
Filename filtering: "contains" is misleading

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1011]
The filename filter on the granule page says "Filename Contains: {{value}}" but it actually only matches when the `value` is a full, verbatim token that has been parsed out of the `title` field in the granule.

For example, if the `title` of a granule is `HS_H08_20190912_1920_B09_FLDK_R20_S0410.DAT.bz2` (an example from Himawari-8 data), a search for `20190912` returns *zero* results. The entire filename is analyzed as a single token and hence a section from the middle of the filename does not match any tokens.

Options:
- wrap the input `value` with something `/.*` and `.*/` to turn it into a regular expression
    - note: this does not appear to work if you put the entire filename in as the value
    - also: searching with a _leading_ `.*` specifically will force the query to touch every single granule in the collection, which could easily be millions
- use an alternate tokenizer when indexing granule `title`s which splits tokens based on common filename delimiters, like `-` and `_`, e.g. the [Simple Pattern Split Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-simplepatternsplit-tokenizer.html)
    - note: would require a full re-index
    - also: would have to verify that we could still search with the full filename
- provide a drop-down to chose between "contains" and "matches" behavior

More discussion is needed to determine the right thing to do here.

**Comment by zebdelk** [comment]
Idea to revise user experience and fix the problem:

use the same sentence-with-dropdown as the relation filter concept to provide "contains", "starts with" and "ends with" options, disallow regex directly in the entry field with validation errors, and wrap the query with the correct regex for users.

**Comment by ajakz** [comment]
Plan to resolve this:
- [ ] Add new `filename` field
- [ ] Add custom analyzer to mappings with: 
  ```
  "tokenizer": {"type": "pattern", "pattern": "([^\\p{L}\\d]+)|(?<=[\\p{L}&&[^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"},
  "filter": ["lowercase"]
  ```
- [ ] Index filename field with custom analyzer
- [ ] Send search request for filename contains request with query parsed with custom analyzer  (this might be taken care of, but need to verify -- https://www.elastic.co/guide/en/elasticsearch/reference/7.5/analysis.html#search-time-analysis)

**Comment by ajakz** [comment]
Revision of plans! Two things have thrown a bit of a wrench into things:
1. The filename is located in the `fileIdentifier`, `title`, or part of the download link URL in ISO.
2. The actual filename is not always useful for narrowing granule results.

So the new plan is:
- [ ] Add new fields to granule mappings: `filename` and alternatively tokenized versions of `title` and `fileIdentifier`
- [ ] Extract filename in DefaultParser from the `FileInformation` 
- [ ] Extract filename in ISOParser -- maybe? -- from download link URLs. It's okay if this ends up not being included, as doing this might require too many awkward assumptions
- [ ] Add custom analyzer to mappings (parse tokens on camel case, with underscores, dashes, and other standard word delimiters) with: 
  ```
  "tokenizer": {"type": "pattern", "pattern": "([^\\p{L}\\d]+)|(?<=[\\p{L}&&[^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"},
  "filter": ["lowercase"]
  ```
- [ ] Index filename field with custom analyzer
- [ ] Add new query or filter type to search API to support this. "Granule Name Filter" is about what we've got so far... 
  - This should allow the user to specify the field to query against, or `all` for the complete set
- [ ] Update the UI
  - Rename filter section filename -> name
  - Use the new search feature directly
