### ISSUE TITLE
Improve `ensureIndex` behavior

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1013]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>operator</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       only run ES initialization logic at startup
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>reduce log noise and ES cluster pressure</td>
  </tr>
</table>

### Description
Currently we run all of the following on *every single batch of inserts into elasticsearch*:

```groovy
esService.ensureStagingIndices()
esService.ensurePipelines()
esService.refreshAllIndices()
```

This results in 2 `HEAD` requests followed by 2 `PUT`s with full index mappings (one for each staging index), 1 `GET` request to check for the pipelines, and 5 separate `POST` requests to trigger refreshes on all indices, including the public-facing search indices. In production this could result in tens or even hundreds of operations being triggered in the ES cluster _every second_.

All of these operations are things that could be done once on application startup and then never again under normal operating circumstances. If the indices/pipelines get deleted out from under our apps at runtime then we'll start seeing the errors and will know that work needs to be done to restore them. In fact we wouldn't want for our app to silently recreate the indices/pipelines in that case, because we would have lost all previously-ingested data with no `ERROR` message at all.

### Acceptance Criteria
- [ ] Run `ensureIndices` and `ensurePipelines` once at application startup
- [ ] Remove calls to `ensureIndicies`, `ensureStagingIndices`, `ensureSearchIndices`, and `ensurePipelines` that will be called over and over as data is ingested
- [ ] Evaluate when `refreshIndices` is being called and only call it when truly necessary, and only on the required indices
    - for example, we could refresh only the staging indices after completing a `_bulk` request or maybe (once!) before queries required for ingest
    - there should be no reason to refresh the search indices at all

**Comment by dneufeldcu** [comment]
- [ ] ElasticsearchConfig constructor can ensure indices once (this doesn't need to happen per request).

**Comment by mcquinne** [comment]
Starting down this path has created more work than anticipated in `admin`, so we're going to let it go in that module and implement it in the new `indexer` instead. In other words this will be covered by #1051 now instead.
