### ISSUE TITLE
Upgrading to Spring 2.2 or greater...

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#1015]
According to Spring Boot Releases [documentation](https://github.com/spring-projects/spring-boot/releases):

`@Component cannot not longer be used on @ConfigurationProperties beans #18138`

A quick skim through onestop revealed we were using `@Component` on `@ConfigurationProperties` in several places. We should address this (maybe simply removing `@Component` would work without issue -- but we should check this has no breaking effect) before upgrading to Spring 2.2+

**Comment by mcquinne** [comment]
Upon further review the issue in question is actually a *bug*, reporting that not being able to use those annotations together is unacceptable. The bug is resolved now, meaning that is *is* possible to use those annotations together, as demonstrated by d62c0b7e as part of #1026.

**Comment by mcquinne** [comment]
In other words I believe there's nothing more to do here.
