### ISSUE TITLE
OneStop CLI + SCDR CLI first pass

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1020]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>User of the OneStop API, specifically algorithms using SCDR CLI</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       Use the OneStop search API with a CLI 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>Have a convenient tool for developing against OneStop's API, and begin porting the SCDR CLI functionality to OneStop</td>
  </tr>
</table>

Related tasks
- [x] Identify language to use to support development of new SCDR CLI utility (ALL)
- [x] Develop standalone executable that can be containerized (Dev team at NCEI)
- [x] Get list of collections currently available in SCDR (STAR)
- [x] Get sample outputs from existing scdr-files utility for options below. (STAR)
- [ ] Identify changes needed OneStop API to fully support existing scdr-file utility options. (Dev team at NCEI)

**Comment by StrayCat1** [comment]
Regarding language- we prefer to write this is GO as it can be packaged as a binary into the container easily and as a team we would like to start using GO more frequently.

It is my opinion that client applications like these be generated from documentation, specifically the OpenAPI spec. When the spec changes, the client can be re-built to reflect those changes easily. Toward that end, the developer community have created projects that can take an OpenAPI specification and create fairly well wrought out CLI tools. Specifically, I am looking at two projects like this - 

https://swagger.io/tools/swagger-codegen/
https://github.com/danielgtaylor/openapi-cli-generator

The first one is built and maintained by swagger and can generate client applications in a variety of languages. The other is a similar project that focuses on GO clients.

**Comment by StrayCat1** [comment]
I have been using a client created by the openapi-cli-generator. Here is my review- 
- simple, easy to get started
- helpful, '--help' flags can display info about endpoints,  methods, and parameters. 
- multi-server support with --test flag
- param aliases with openapi extension properties
- waiters for async actions 
- limited, nested objects in args are not parsed properly
- abandonware? not as well maintained as swagger codegen (small number of contributors). 

Examples- 
Find collection by fileIdentifier- `onestop-cli searchcollection --verbose queries[]{type:queryText, value:fileIdentifier:\"gov.noaa.nodc:NDBC-COOPS\"}`

Find granule by parentIdentifier - `onestop-cli searchgranule --verbose queries[]{type:queryText, value:parentIdentifier:\"gov.noaa.nodc:NDBC-COOPS\"}`

Find granules by regex parentId- `onestop-cli searchgranule --verbose queries[]{type:queryText, value:parentIdentifier:/.*NDBC-COOPS/}`

Find granules by date - onestop-cli searchcollection filters[]{ type:datetime, after:2000-01-01T00:00:00Z, before:2017-01-01T00:00:00Z} --verbose

**Comment by StrayCat1** [comment]
Trying out swagger codegen

**Comment by StrayCat1** [comment]
Status update - 
We have implemented a CLI with some of the SCDR functionality. At this point I think we can sharer what we have with STAR folks and help them implement additional functionality. 

I am working on a way to manage the CLIs dependencies, package them, and create an image that contains all the necessary dependencies, from go to our package, so that it can be run anywhere. 

At the moment I am facing two hurdles - 
1) speccy is creating $refs that the openapi-cli-generator tool doesnt know how to resolve (any $ref to objects not under #component/schemas. Other have raised this issue with speccy because it doesnt play nice with other openapi tools. There is also an issue to update the go package that parses there $refs. However even if that gets fixed, we would still end up with a spec that is not well organized so I am hoping speccy comes up with something. Otherwise my only choice is to try and organize the way these yaml/json files reference one another so everything ends up under component/schemas. So far I have been unsuccessful with that and am leaning toward manually fixing the openapi spec (which is obviously not ideal). 

2) gogradle works well for dependency resolution, testing, and ensuring proper go lang formatting. However, I am having trouble getting everything packaged into an image. 

Here is what is left on my todo for this story- 
- [ ] organize code so flags and parsing methods can be shared by onestop-cli command and scdr-files command
- [ ] Build CLI from latest OpenAPI spec 
- [ ] change print statement to log statements (use log library provided)
- [ ] update readme with flags, examples, and notes for developers.

**Comment by StrayCat1** [comment]
We have implemented a few scdr-files use cases as best we can given the current state of OneStop functionality.  We have numerous examples of how to implement a subcommand and flags to support more use cases. We have also implemented a continuous integration pipeline that generates the CLI tool during build. This ensures the CLI is up to date with the tests in the search module. 

Examples of scdr-files implementation can be found here - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/cli/scdr-files.go
and here https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/cli/scdr-flags.go

Check the readme for the numerous ways of building and using the cli. https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/cli/README.md

Outstanding issues - 
- [ ] onestop-cli image is still too big! ~800Mb
- [ ] circle ci doesnt seem to be caching. 

Also in the works is a github page and a document with a comparison of scdr-files functionality and what OneStop can provide.

**Comment by dneufeldcu** [comment]
For the demo we plan to use GOES16 ABI radiances.

**Comment by StrayCat1** [comment]
List of collections in SCDR 
https://docs.google.com/spreadsheets/d/1-UUS0AgUJ0Yn5wEnhBV9jyHGRWXIEHJsl2XC2YoACPY/edit#gid=0

**Comment by StrayCat1** [comment]
The CLI is ready and will not effect the functioning of existing apps. 

However, this branch also contains changes to how we validate incoming requests that could possibly break something. That said, the tests that were added to confirm no breaking changes were introduced is satisfactory. I can say with a reasonable amount of certainty that these changes will not result in a change in behavior from that which is currently deployed.
