### ISSUE TITLE
Determine branching strategy for 3.x work

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1024]
### Background
The work of epic #1035, #1036, and #1021 will take some time to complete and the system may not be fully functional during the transition from separate psi and onestop systems into a consolidated platform. We need to determine where to do this work so that we still have the ability to apply bug fixes, security updates, etc. to the 2.x version of onestop running in production while this work is in flight.

### Options
- Place the `release/2.x` branch at the latest 2.x tag and do any hotfix-type work there
- Create a `release/3.x` branch and merge the work of these epics into it *instead of master*
- ... others?

### Acceptance Criteria
- [x] Meeting held
- [x] Decision made

**Comment by dneufeldcu** [comment]
Upon further review, no branching strategy is required!

We will merge changes into the master branch directly, and the key will be that we **maintain the existing artifacts** in the process. In particular, the `admin` module -- which will eventually have its indexing logic factored out into a separate `indexer` module and its api endpoints migrated to the `registry` module -- will continue to exist and be maintained as-is until we know that it is no longer being deployed.
