### ISSUE TITLE
Consolidate helm charts and skaffold setup

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1027]
### AC:
- [x] A single chart exists which can deploy the entire platform
- [x] The chart is still comprised of the existing sub-charts for each component
- [x] Skaffold can fire up everything in the system
    - [x] Consider creating additional skaffold profiles (there are a couple in the psi skaffold already) to support only firing up subsets of the stack for local development
- [x] Names are consistent, e.g. rename `psi-registry` to `onestop-registry`

**Comment by Ghebrechristos** [comment]
Skaffold does not seem to support multiple profile: 
https://github.com/GoogleContainerTools/skaffold/issues/2535
