### ISSUE TITLE
Consolidate root-level files

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1031]
### AC:
- [x] The main readme is updated with info about the entire platform (pay special attention to `Legal` sections)
- [x] The `license.txt` is updated as needed to represent both projects (maybe nothing needed?)
- [ ] All other files that were at the root level of `psi/` are moved/merged/represented at the onestop root level

**Comment by Ghebrechristos** [comment]
The license is generic so nothing to do there.
