### ISSUE TITLE
Pagination of List Views

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#1058]
Currently, our `ListView` component, uses a special-case of infinite-scroll (using a button to trigger "more results"). This implementation causes issues when trying to manage a variety of cases where the items displayed by the `ListView` component changes, primarily handling focus for keyboard users.

In order to address this complexity, we have decided that a `PageView` component should replace the `ListView`. This component would similarly handle the `grid` and `list` components as `ListView` handles today, but the complexity of managing focus would be eliminated by adhering to a more predictable pagination model.

Desired features:

- Page Size Options: (5, 10, 25, 50, 100)
- First Page, Previous Page, Next Page, Last Page
- etc...

See this component for inspiration on props:

https://github.com/codenaz/react-paginator

It would be desired to borrow their fxn'al convention and pagination logic, but make our own custom component w/similar documentation, because they use `className` based styles and it would be a bit unusual in the context of our style conventions.

**Comment by zebdelk** [comment]
success criteria for the focus stuff:
- [ ] remove attempts to track focus among result items
- [ ] loading a different page should either leave focus entirely alone, or at most, move it to the top of the newly loaded content (currently leaning towards no change, but we should talk through the different users and make sure that makes the most sense)

**Comment by dneufeldcu** [comment]
Need to focus on sorting first.

**Comment by StrayCat1** [comment]
I made a change in search to always sort by _ID as well as _score. Something like this- 
```
requestBody.sort = [
        "_id": ["order": "desc"],
        "_score" : ["order":"desc"]
    ]
```

Which I had lumped in with this pagination story as a way to prevent duplicates. I havent been able to confirm if this works however. And it isnt exactly like a "sort option" because users can't choose it and it's always on.

**Comment by StrayCat1** [comment]
I did not add that sorting parameter to api-search on this branch. 
That will be the default in #1119

**Comment by StrayCat1** [comment]
Also, I did nothing with the focus. We should create a story for that if necessary.
