### ISSUE TITLE
Documentation for loading Metadata into OneStop v3 

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1061]
### AC:
- [x] Update docs to only include instruction in how to load metadata via registry api

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/blob/master/docs/metadata-manager/v3/onestop-metadata-loading.md

**Comment by StrayCat1** [comment]
Couple things for future consideration - 
1) PUT and PATCH look the same. We may want to distinguish the two. 

2) We may want to link the schemas for uploading json. 

These are things we can come back to as users familiarize and utilize the docs.
