### ISSUE TITLE
Documentation for connecting Upstream application to kafka broker

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1067]
AC: 
Document some approaches for integrating upstream applications and Kafka. 
- [x] Apache NIFI 
- [x] Kafka Producer 
- [x] Kafka Connect

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/blob/f08a882f631597ab2045c175a9d5def8d938f76a/docs/metadata-manager/v3/upstream-kafka-connect.md
