### ISSUE TITLE
Metadata loading updates

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1071]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops specialist</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       use the same metadata test package for on-prem or cloud instances of OneStop
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>continue to have a consistent and simplified process</td>
  </tr>
</table>

### Tasks
- [x] Metadata updates
  - Satellite collection metadata records loaded
  - Jason L0, L1 records assigned UUID added to test package and loaded 
    - L0: https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.nodc:0122599/xml
    - L1: https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.nodc:0122597/xml
  - psi-os-nesdis-demo leverages onestop-test-data and is just used as loading scripts for cloud instance

**Comment by mcquinne** [comment]
The metadata has been added to the [test data repo](https://github.com/cedardevs/onestop-test-data/tree/master/GOES), loaded into the cloud OneStop and is available under a [SCDR File Demo collection](http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop/collections/details/5b58de08-afef-49fb-99a1-9c5d5c003bde).

**Comment by StrayCat1** [comment]
http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop/collections/details/5b58de08-afef-49fb-99a1-9c5d5c003bde

Looks good
