### ISSUE TITLE
Generated location filters not the same when created with map vs text entry

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1079]
## Summary
Creating a location filter requires us to hand off coordinates between the URL, leaflet map, and text entry boxes while doing some coordinate shifting to render everything correctly in all 3 spots (correct image plus -180 to 180). If we start a search with a drawn filter, everything works correctly when crossing the IDL and PM. However, the exact same coordinates entered into the text boxes will create an inverse polygon and send the wrong request to ES.

Screenshot of behavior when creating filter by drawing:
<img width="1446" alt="Screen Shot 2019-11-13 at 3 14 12 PM" src="https://user-images.githubusercontent.com/5514537/68809962-4db01580-062a-11ea-83f4-0b38a8591586.png">

Screenshot of behavior when creating filter by manual text entry (in this case I just removed the decimal values from the West and East coordinates):
<img width="1446" alt="Screen Shot 2019-11-13 at 3 30 44 PM" src="https://user-images.githubusercontent.com/5514537/68810361-33c30280-062b-11ea-92e3-f735e2433d14.png">

## Expected Behavior
The UI should draw the correct bounding box and send the correct query regardless of how the location filter was created by the user.

## Extra
Taking care of this might also resolve when rendering a collection map is incorrect, or it may not. Probably need to create another issue if this doesn't get resolved too: http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop/collections/details/11111111-1111-1111-1111-111111111111

**Comment by zebdelk** [comment]
started a branch for this, 1079-fix-location-filter-inconsistency
so far all I've done is refactor the geometry filter into a functional component. I think the effect is going to be the best place to sort out what the values are for display, vs what needs to be stored in redux (much like was the case for format changes with geologic dates)

**Comment by zebdelk** [comment]
might be related to https://github.com/cedardevs/onestop/issues/457? Note to self: reread that one.

**Comment by zebdelk** [comment]
**Very important observation by Chris:** We should decide if this is something we're fixing in the API, when submitting a geologic filter search to ES. I'm currently assuming part of the solution will involve shifting coordinates, much like we expect to do when we index the collection that revealed this bug. If we only fix it in the UI, the CLI will still be subject to valid-looking searches.

**Comment by ajakz** [comment]
Re @StrayCat1 's observation: #1080 was opened to index our geometries with +/-360 so that ES doesn't swap our indexed geometry shapes around.

However, the key with this UI issue is:
>  If we start a search with a drawn filter, everything works correctly when crossing the IDL and PM.

This issue is fixing the discrepancy between the searches generated when creating the filter with the map vs with the text boxes, which definitely needs to be addressed as well since it's separate from how we index things in ES. The screenshots above show that we're sending different but accurate coordinates (shifted by 360 degrees) when creating the filter from the map.

PS @zebdelk I think #457 is the same issue, so you can consolidate these two.

**Comment by dneufeldcu** [comment]
we're planning on changing the search api, so the only piece that is still a UI bug is that the search query renders incorrectly when entered from the text boxes
