### ISSUE TITLE
Empty cart contents should ask if you're sure

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1086]
## Summary
When on the cart view page, clicking the "Empty Cart" button doesn't have any sort of "Are you sure?" confirmation, but given the gravity of what it does it probably should. (This keen observation brought to us by @kenhtanaka!)

## Tasks
- [ ] Have a pop-up of sorts to confirm this is what the user definitely wants to do

**Comment by erinreeves** [comment]
Suspect this works for 508 compliance:
https://reactcommunity.org/react-modal/examples/minimal/

**Comment by zebdelk** [comment]
No obvious sources found for Safari related bugs

**Comment by dneufeldcu** [comment]
Cross browser support.
