### ISSUE TITLE
OneStop(IM) Standard Operating Procedures

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1091]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>an organizational process</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       document the standard operating procedures for our software
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>can be confident in my CM practices</td>
  </tr>
</table>

### Background
Our organizational process requires an SOP for software as part of the ORR.

### Tasks
- [ ] Create a google doc or suitable alternative for our partner environment on deployment and operations of the OS/IM stack

Note - needed prior to ORR target 12/9/19

**Comment by Ghebrechristos** [comment]
Google doc link: https://docs.google.com/document/d/1ynqrPdN-FA-MBKDcwbGK-VdkPxorPSEqDhWr7KZ5IxA/edit

**Comment by StrayCat1** [comment]
related - https://github.com/cedardevs/onestop/commits/master/docs/metadata-manager/v3/onestop-metadata-loading.md

**Comment by StrayCat1** [comment]
SOP looks good and ready for user feedback.  We added some steps to confirm the backing services and our applications are working.
