### ISSUE TITLE
Sanitize IDs before initiating inter-registry requests

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1105]
Before initiating requests from one registry instance to another in `MetadataStore` we need to sanitize the ID (which came from the incoming REST request) to avoid any chance at SSRF attacks.

Probably just a quick check that it is alphanumeric, `-`, or `_`?

**Comment by dneufeldcu** [comment]
Decision upon further discussion:

1. Enforce that IDs are UUIDs in the MetadataRestController, like we are in the PublisherController
2. Add a filter to the input topic handles which drops messages with non-UUID keys and logs an error message

**Comment by Ghebrechristos** [comment]
Add this logics to the psi repo and push code to gitlab as well (or let Semere know when you done with this review).
