### ISSUE TITLE
Remediate security issues for Inventory Manager

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1107]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>security officer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       confirm findings have been addressed.
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident in our system posture</td>
  </tr>
</table>

##Tasks
- [ ] Remediate security issues for Inventory Mananger see WD-577

**Comment by Ghebrechristos** [comment]
Security scan will be submitted by Dave!
