### ISSUE TITLE
Identify admin tasks/endpoints   

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1113]
Identify the Admin API tasks and make sure if it is covered by the registry API 

The merged API should:
- Cover all the administration tasks

**Comment by Ghebrechristos** [comment]
Admin endpoints: 
-[ ] /admin/index/metadata/recreate : to recreate the staging index 
-[ ] /admin/index/metadata/recreate : to recreate the search  index

**Comment by Ghebrechristos** [comment]
Upload controller? no need for manual metadata upload since people are starting to pick up steam in using kafka upload

**Comment by Ghebrechristos** [comment]
Read endpoint ? 
What is in kafka may not be indexable, so should we add an end point in registry to get staff out of ES ? or add a field that indicate if a metadata is indexed/not indexable

**Comment by Ghebrechristos** [comment]
Security service can be remove as well. checked with the security expert @forgo

**Comment by dneufeldcu** [comment]
We should continue to support HTTP based uploads, I expect there will be networking issues with kafka for remote metadata content authors.
