### ISSUE TITLE
EPIC: Authz in APIs

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#1126]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>{stakeholder role}</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>sign in to my secure dataset in registry api </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>manage my dataset</td>
  </tr>
</table>

### Description
{description}

### Assumptions
- {assumption 1}

### Fill in tasks after subsetting design discussion 
- [ ] first task 
- [ ] second task 
- [ ] third task 

### References
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>{name|email|room#|phone}</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>{link}</td>
  </tr>
</table>

**Comment by ajakz** [comment]
closing due to lack of details and movement
