### ISSUE TITLE
Verify message compression is working

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1127]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>operator</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       verify that message compression is working
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>save disk space and network usage, and be sure that collection xml will fit!</td>
  </tr>
</table>

### Description
While preparing for the recently cloud demo, several collections from the `onestop-test-data` repo triggered Kafka error messages indicating that they were too large to be sent to the broker when being uploaded through the `psi-registry` REST API. The sizes indicated in the error messages where only slightly larger than the size of the XML file on disk, implying that the XML content was not being compressed before being sent to Kafka.

### Acceptance Criteria
- [x] All the collections from the `onestop-test-data` repo can be published to the `psi-registry` API and subsequently sent to Kafka without size errors
- [x] Large collection records provided by collection manager team can be uploaded

**Comment by Ghebrechristos** [comment]
When the file is larger that 1MB, it throws an error: 
``` html 
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.6</center>
</body>
</html>
