### ISSUE TITLE
Update ES mappings for scdr-files

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1129]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>scdr-files user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       use scdr-files flags  --sha1 , --since, --doy, --month, --day 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>use the OneStop CLI (scdr-files subcommand) in lieu of the scdr-files cli and backend</td>
  </tr>
</table>

We need to update the ES indices to support the aforementioned flags. 

SHA1 - PSI has file level information already, so all we need to do is to index that data in OneStop
Since - requires the results come back sorted by date, OR we make stagedDate a searchable/sortable field. 
Month and Day - requires we index the month and day of the month for each record

**Comment by StrayCat1** [comment]
To support --DOY, --month, and --day, we can index the start and end DOY as well as start/end month of the year. i.e. ( startDayOfYear, endDayOfYear, startMonthOfYear , endMonthOfYear) 

We also need to account for leap years. So when someone searches uses DOY, we use the correct DOY based on the year of the record.

**Comment by ajakz** [comment]
Reviewed this and looks good after my couple changes merged to the branch already
