### ISSUE TITLE
Usage stats from STAR for scdr-files 

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1131]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer of the scdr-files subcommand on the onestop CLI</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       see the ways in which scdr-files is used most frequently at STAR
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>prioritize essential features and avoid wasting time on flags or syntax that is not used</td>
  </tr>
</table>

**Comment by dneufeldcu** [comment]
Dave F. will send out request to see if stats available.

**Comment by dneufeldcu** [comment]
Matt J. responded with what is available.
