### ISSUE TITLE
Generate sitemap dynamically

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1140]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>foam cat</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       generate the sitemap dynamically from the collection index
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>remove complicated sitemap creation code</td>
  </tr>
</table>

### Background

The current process for sitemap generation is more complicated than it needs to be. It involves a job that runs asynchronously with a scrolling request and the construction of a separate index. Instead, the sitemap could just be built by:

1. For the main sitemap, get the `_count` of collections, divide it by the # of collections per sub-map, and generate references to the resulting number of sub-map pages
2. For each sub-map, simply get that page of collection `_id`s (sorted by `_doc`) and generate references to each one
3. (optional) Periodically cache the results locally

### Acceptance Criteria

- [ ] sitemap construction process is removed from `indexer`
- [ ] the sitemap index is no longer used
- [ ] the sitemap endpoints on `search` still return the same things (maybe w/ different # per page)

**Comment by dneufeldcu** [comment]
Work out concerns around 10,000 search limit

**Comment by mcquinne** [comment]
After further discussion this approach will not work due to the `index.max_result_window` parameter, which defaults to 10k (see: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-from-size).

There may be other options down the road, e.g. to use the registry api to supply the sitemap, but this particular approach simply will not work, so we can close this issue.
