### ISSUE TITLE
Deploy OneStop 2.4.2+ to cloud-sandbox

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1146]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops team</td>
  </tr>
  <tr>
    <td><b>We want to be able to</b></td>
    <td>
       have multiple team members up to date on the cloud sandbox
    </td>
  </tr>
  <tr>
    <td><b>So that we can</b></td>
    <td>be confident in the shared knowledge of the team</td>
  </tr>
</table>

**Comment by StrayCat1** [comment]
Looks like someone did deploy it. 
http://acf3425c8d41b11e9a12912cf37a7528-1694331899.us-east-1.elb.amazonaws.com/onestop/
