### ISSUE TITLE
Saved Search - SQL + Connector state management

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#1148]
First rough-pass could simply save the url (or the JSON serialized filter state which derives it)
one of these "saved" could be as simple as a row in a PostGreSQL for the login-gov id (not email)

```
USER.SAVED_SEARCHES (LIMIT per user_id = 100)
id  | user_id       | name             | description?                                        | filter
123   456             "Jurassic Park"    "OneStop Search for Michael-Crichton-related data"  | { JSON }
```
- [x] Evaluate modern Java frameworks (Quarkus vs Micronaut)
- [x] Db schema is available to store search json
- [ ] ~add REST endpoint to save/edit searches / remove saved searches (by db id) / get (by user id)~ #1184

**Comment by Ghebrechristos** [comment]
Both Quarkus and Micronaut are used to build microservice and serverless applications tailored for JDK and GraalVM and open source project under the Apache License 2.0.

Quarkus: 
-  Created by RED HAT 
-  Development started in 2019 
-  Supports reactive programming
    - Supports Netty and Vert.x as reactive engines that are based on an event-driven architecture with non-blocking IO

Micronaut: 
-  Created by creator of GRAILS (may be red flag) 
-  Development started in 2018
-  Inspired by the Spring and Grails frameworks 
-  Supports reactive programming
    - Includes both non-blocking HTTP server and client APIs based on Netty.

**Comment by Ghebrechristos** [comment]
Team wanted to keep using  Spring , eventually spring reactive for now

**Comment by Ghebrechristos** [comment]
Covered by story

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/tree/1184-userRest/user
