### ISSUE TITLE
Tag and release a scdr-files client update

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1158]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>STAR scientist</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       test the latest features of the scdr-files client
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be confident OneStop will serve as a replacement to my existing catalog/workflows</td>
  </tr>
</table>

- [x] Tag a version of OneStop that supports a version of scdr-files candidate for further testing
- [x] Ensure that nesdis-sandbox has a supported OneStop version in place for the client #1146
- [x] Make any updates needed to README file and highlight new arguments supported from last release
- [x] Add h8 collections to client config for lookup by type (get from Matt J. if needed)

**Comment by mcquinne** [comment]
Spreadsheet of Himawari datasets and corresponding collection IDs (for updating the config file): 
https://docs.google.com/spreadsheets/d/1IdGO1GEn-LeZI9FFGO9WrK6gRx7xbWm1eQkORGCQyXg/edit?usp=sharing

**Comment by Ghebrechristos** [comment]
Added h8  product tag and UUID 
```json
AHI-L2-FLDK-Cloud-Height: fca80472-dc74-45af-b1e5-240dfd56f6ba
  AHI-L2-FLDK-Cloud-Mask: 51a1acc3-d304-4e1a-b9c7-6ff9aedf24da
  AHI-L2-FLDK-Cloud-Phase: 527c9d2d-0059-4594-81d9-0909da8c9ba2
  AHI-L2-FLDK-Derived-Motion-Winds: 04fa6e98-9c32-491b-93ea-cfde2bd105a9
  AHI-L2-FLDK-Derived-Motion-Winds: 04fa6e98-9c32-491b-93ea-cfde2bd105a9
  AHI-L2-FLDK-Derived-Motion-Winds: 04fa6e98-9c32-491b-93ea-cfde2bd105a9
  AHI-L2-FLDK-Derived-Motion-Winds: 04fa6e98-9c32-491b-93ea-cfde2bd105a9
  AHI-L2-FLDK-Derived-Motion-Winds: 04fa6e98-9c32-491b-93ea-cfde2bd105a9
  AHI-L2-FLDK-Derived-Motion-Winds: 04fa6e98-9c32-491b-93ea-cfde2bd105a9
  AHI-L2-FLDK-RainfallRate: 0f1bf7d1-5c53-446c-b32a-422336d7c5e0
  AHI-L2-FLDK-Sectors: 1736262d-9bb3-4381-a7b6-696cd9579572
  AHI-L2-FLDK-ACSPO-SST: 351cd13c-ba0a-4a36-8c17-7dede9406518
  AHI-L2C-FLDK-SST: 178d46ed-0abc-4ec5-a138-39a8a6ee9848
  AHI-L2P-FLDK-SST: 97dbe034-d544-4f12-95af-38cebef96b5d
  AHI-L3C-FLDK-SST: 741eea48-5736-4b5f-9935-222aad67be65
  AHI-L3U-FLDK-SST: d578aa02-183d-4cc8-b9e0-56743923723d

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/releases/tag/v3.0.0-alpha3

**Comment by StrayCat1** [comment]
Added the CLI binaries and current config to the release artifacts.
