### ISSUE TITLE
EPIC: Support streaming flattening

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1171]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>downstream consumer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      listen to flattened granules
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>use the flattened granule information</td>
  </tr>
</table>

### Tasks
- [ ] Part 1 - Flatten incoming granule based on its parent
- [ ] Part 2 - Reprocessing when a parent / collection changes

**Comment by dneufeldcu** [comment]
Let's discuss in parking lot and get team input on possible approaches.

**Comment by dneufeldcu** [comment]
Schedule design discussion as next step.

**Comment by mcquinne** [comment]
Been thinking a lot about this and came up with a straw man for further design discussion.

![RB 2020-04-10 16.53.04.jpg](https://images.zenhubusercontent.com/5ca4dc0f956d8a50473e93bd/e174b1f7-62ed-464c-8327-9bd7870770d6)

**Comment by ajakz** [comment]
Thoughts from design discussion:
- Make pro/con table of different discussed approaches
  - KTable
  - Separate topics
  - ES flattening
  - Using another DB
  - A combination of the above approaches based on a collection's granule count (e.g., flattening in ES for smaller collections but with KStreams for large collections; etc.)

**Comment by zebdelk** [comment]
pointed out by Semere: look into existing tools to solve this so we don't reinvent the wheel
