### ISSUE TITLE
Onestop Test Data not associating granules to collections correctly

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1180]
## Description
The upload script needs to send an additional JSON request to IM specifying the collection relationship for XML files, but our manifest files as generated do not have that information. The upload script currently assumes granules appear after their parent collection in the generated manifest files. Either we need to update the manifest file generation code to actually produce this (somehow...) or change how metadata is organized so it's easy to programmatically link records (like putting grouped granules in folders with their collection's UUID as the name?). In the meantime, granules are not being associated to the correct collections in cases where the test data type has more than one collection.

**Comment by StrayCat1** [comment]
Updated manfiest.sh to organize granules under their collection. This enabled the changes Arianna made to upload.sh to work.

**Comment by ajakz** [comment]
NOTE: If granule XML has DOI in parentIdentifier field, manifest.txt is not generated correctly. Need to update to enable support for both. Talking with @StrayCat1:

> can probably just use a regex to find the DOI in the collection, and then add that to our grep for granules

`GRANULE_FILES=$(grep -rlE "($IDENTIFIER|$UUID)" $BASEDIR/granules)`

`GRANULE_FILES=$(grep -rlE "($IDENTIFIER|$UUID|$DOI)" $BASEDIR/granules)`
