### ISSUE TITLE
Design UI flow with login

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1185]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>application developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       understand the UI flow for success/failure conditions
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>see the saved search when successfully logged in or alternate flow</td>
  </tr>
</table>

### Tasks
- [ ] Quick wireframes to support success/fail flow
- [ ] State diagram to support flow

**Comment by StrayCat1** [comment]
This has been overtaken by events. Elliott is not longer with us. 

We have a basic idea of how it flows now. As of 7/15, this is what it looks like - 
https://drive.google.com/file/d/1PMzMJitjzsB-plPViSSostCXX7YbwKou/view?usp=sharing

closing
