### ISSUE TITLE
New project for user api

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1193]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       organize saved searches around a user api
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have separation of concerns and reusability</td>
  </tr>
</table>

- [x] create new spring project `user` that is developed/built/tested as our other APIs
  - [x] gradle integration
  - [x] helm chart
  - [x] skaffold
  - [ ] circle integration
  - [ ] unit tests
  - [ ] integration tests
  - [ ] pac4j integration

**Comment by StrayCat1** [comment]
Associated branch- https://github.com/cedardevs/onestop/tree/1184-userRest/user
