### ISSUE TITLE
Apply bounding coordinates NaN

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#1198]
The UI shouldn't let you accidentally enter NaN for your bounding coordinates.

![Screen Shot 2020-03-17 at 8.39.52 AM.png](https://images.zenhubusercontent.com/5cb0c19d97df763a9090b607/5339d9a3-fcea-4912-be51-ef9439b933dc)![Screen Shot 2020-03-17 at 8.39.47 AM.png](https://images.zenhubusercontent.com/5cb0c19d97df763a9090b607/b131f49e-7fd9-4c16-904c-ae40c72e6ccc)![Screen Shot 2020-03-17 at 8.39.40 AM.png](https://images.zenhubusercontent.com/5cb0c19d97df763a9090b607/2dee0e81-3cc6-4cf6-b50a-e416b2c2eb7d)

## To reproduce:

Open the location filter. Without typing anything, hit "Apply".
Alternatively, add `&g=NaN,NaN,NaN,NaN&gr=i` to the URL

## Expected behavior
- [x] hitting Apply with a blank form should either ignore the request or display the "invalid coords" error messages *without* also applying the filter
- [ ] ~putting NaN,NaN,NaN,NaN in the URL should drop that as a filter.Ex: http://localhost:8888/onestop/collections?q=gist&g=NaN,NaN,NaN,NaN&gr=i~
- [ ] ~select a valid bounding box. In the URL, change one of the numbers to NaN. This should *NOT* go through as a valid bbox (it does, currently)~

**Comment by erinreeves** [comment]
Created story #1219 so crossed out duplicate requirements in this story.

**Comment by erinreeves** [comment]
resolves #123
