### ISSUE TITLE
IM spin-up

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1199]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       transition to supporting GIS integration
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>contribute to the code base</td>
  </tr>
</table>

- [x] Follow readme and docs (https://github.com/cedardevs/onestop/tree/master/docs)
- [x] Improve readme

**Comment by kenhtanaka** [comment]
[Notes to Improve the Internal Developer Quickstart Doc](https://docs.google.com/document/d/1tJkFEn7AOiDHbGFBH0sfA4h_T1SAdmunfb-dTDswyf4/edit?usp=sharing) work in progress
