### ISSUE TITLE
Spike: indexer with configurable consumer group name

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#1207]
- [ ] pros/cons of doing this to reprocess from zero?
- [ ] watch out for leftover data / topics

### Background
- [ ] how to persist data in ES volume

**Comment by dneufeldcu** [comment]
Improve metadata loading in dev

**Comment by dneufeldcu** [comment]
Story came up as bad state of cluster

**Comment by StrayCat1** [comment]
overtaken by events- went with #1325
