### ISSUE TITLE
Docker implementation support for ES 2.4.x

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#121]
AC: Can run docker compose and ES on 2.4.x and API works.

**Comment by aaronjcaldwell** [comment]
[]- Use Docker Compose to run API in container
[]- Use Docker Compose to run ElasticSearch in container
[]- Confirm API and ES can communicate with each other from within containers
[]- Document how to start and access ES and API
Bonus round:
[]- Mount external location for ES indices

**Comment by ajakz** [comment]
What's committed to the Docker branch currently supports pointing directly to a developer's local ES data, then spinning up a single-node ES cluster that works with the API and client. There should be a cleaner organization of this (and the future ES 5.x setup) in the directory structure, along with some thought into how we can migrate our gradle scripts to utilize docker.
