### ISSUE TITLE
Consolidated Catalog demo prep

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1211]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Cloud IPT member</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      demo the catalog to the inter-agency review team
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>can have the IPT work reviewed.</td>
  </tr>
</table>

- [x] Document catalog endpoint for Patrick
- [x] Ensure Himawari8 data is loading
- [x] scdr-files is available and working against the prod catalog endpoint from an aws workspace

**Comment by mcquinne** [comment]
Additional tasks for next demo:
- [ ] add official H8 collections to the catalog (same collections as from #1216)
- [ ] update metadata extraction code to put granules under their collections (coordinate with algorithm team)
- [ ] reorganize the millions of granules that had been put under the placeholder collection into the correct collections
    - use scdr-files?
    - create one-off sme script?
    - leverage lambda somehow?

**Comment by mcquinne** [comment]
Takeaways:
- Creating a python consumer with avro deserialization was non-trivial, but has been accomplished. see: https://github.com/cedardevs/sme-tools
- We **badly** need to focus on providing a path for data managers to do bulk updates like moving granules from one collection to another. Creating a script which reads all of Kafka, filters out most of the stream, fires off multiple API requests is just way too high of a bar for our data managers. Plus it's just not a terribly pleasant experience.
    - I do think that our streaming flattening work could lead us directly into the space of supporting bulk operations, at least at the collection level, see: #1171
