### ISSUE TITLE
Add number formatting to collection overview page

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1220]
We have javascript code that we use to format numbers to be more human-readable, in use on the about page (http://9bcc428b-default-osclient-d008-199379672.us-east-1.elb.amazonaws.com/onestop/about) and also the granule list (http://9bcc428b-default-osclient-d008-199379672.us-east-1.elb.amazonaws.com/onestop/collections/granules/11111111-1111-1111-1111-111111111111).

However we are not applying that formatting to the collection detail page yet (http://9bcc428b-default-osclient-d008-199379672.us-east-1.elb.amazonaws.com/onestop/collections/details/11111111-1111-1111-1111-111111111111).

Tasks:
- [x] Apply the formatting to the number of granules on the collection details page.

**Comment by erinreeves** [comment]
Steps to reproduce locally:
Loaded hazard data into local repo:
./upload.sh IM HazardImages localhost/registry

http://localhost:8888/onestop/collections/details/075a3799-d02d-488b-b9de-a265e8905655
