### ISSUE TITLE
Migrate public user login from search api to user rest api

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1229]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>software development team</td>
  </tr>
  <tr>
    <td><b>We want to be able to</b></td>
    <td>
       have clear separation of concerns in our API
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>the code is clear and more maintainable</td>
  </tr>
</table>

### Tasks
- [x] Migrate login code from search api to user api
- [x] Integrate user identity with database persistence for saving searches

**Comment by dneufeldcu** [comment]
Put it in kubernetes

**Comment by dneufeldcu** [comment]
Working on service integration between user api to get openid profile

**Comment by StrayCat1** [comment]
Work is occurring in the User branch- https://github.com/cedardevs/onestop/tree/1184-userRest
 
As of 6/23-
- we have a spring reactive (webflux) project, gateway, that knows how to proxy requests in a scalable, nonblocking way. Any paths matching `/api/{service}/` will be proxied to that `service` to one of the matching  `routes` in the config-
```gateway:
  routes:
    user: http://localhost/user
    onestop: http://localhost/client
``` 
 
- gateway is based on the details laid out here, but with some critical differences listed below- 
https://developer.okta.com/blog/2017/12/18/spring-security-5-oidc

- gateway uses the "auth code flow" (`private_key_jwt`) to complete oauth2 and oidc protocols. Read more about the sequence of requests here- https://developers.login.gov/overview/
and here - https://developers.login.gov/oidc/
- gateway uses a public/private cert to carry out `private_key_jwt`. The app and its public key are registered with login.gov ahead of time here. More on how to do that here- https://developers.login.gov/testing/
- the private key is mounted to the gateway pod 

- gateway is secured with spring security and configured to use login.gov oauth2 + oidc. Reference the authcode flow against these configurations- 
```spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          login-gov:
            client-id: "urn:gov:gsa:openidconnect.profiles:sp:sso:noaa:onestop_user_8080"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
        provider:
          login-gov:
            authorization-uri: https://idp.int.identitysandbox.gov/openid_connect/authorize?acr_values=http://idmanagement.gov/ns/assurance/ial/1
            token-uri: https://idp.int.identitysandbox.gov/api/openid_connect/token
            user-info-uri: https://idp.int.identitysandbox.gov/api/openid_connect/userinfo
            jwk-set-uri: https://idp.int.identitysandbox.gov/api/openid_connect/certs
            user-name-attribute: sub
```
- gateway manages a session for each client and stores auth information in-memory using `ReactiveOAuth2AuthorizedClientService` 

- only authenticated users can get through to the protected paths behind `/api/*`


- We have a user app, User, which provides an API backed by postgres
- The User API currently receives a token passed from login.gov (by way of gateway) in the Auth header, which is then uses to get OIDC info from login.gov. 
- That fetch to get user_info may be redundant. Gateway already has the OIDC info, we are working to add it to a JWT and pass it in the proxied request to user.  


- gateway will proxy `/api/user/*` to the user app after the user authenticates 
- gateway has an ingress listening on `/` which means it will pick up any requests that don't hit the more specific ingress paths (e.g. `/onestop`)

- the client can hit an endpoint to Gateway that will redirect to login.gov. After the user grants permission, login.gov will redirect us to the root of gateway (`/`), which in turn redirects us to `/onestop` with a SESSION cookie. 
- now the browser can use that to hit a protected endpoint on the User API to get profile/search information. 

I still need to push some of this. Will do shortly.

**Comment by StrayCat1** [comment]
Hooking the UI saved search components up to the API. The gif below is from earlier this week. Some things have changed, but still mostly accurate. 

Also been catching Semere up to speed on this stuff. 

![Screen Recording 2020-07-06 at 2 44 41 PM](https://user-images.githubusercontent.com/26884996/87082710-ab602600-c1e8-11ea-9a3c-0f2d99b7e762.gif)

**Comment by StrayCat1** [comment]
This aspect is done for the time being. Working on #1274 for the time being.

**Comment by StrayCat1** [comment]
The remaining work on this story has been broken out into their own stories. 

Review can still occur on 1184-userRest, though that branch is still in progress.
