### ISSUE TITLE
Add missing fields to A&E mapping

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#1251]
## Background
The initial first pass of the ES mapping was autogenerated and some fields didn't track over from the avro schemas.

## Tasks
- [x] Find all fields in the analysis.avsc (Schemas repo) that aren't present in the collection and granule ES mappings (elastic-common module in Onestop repo)
- [x] Fix by adding the fields to analysis.avsc

**Comment by erinreeves** [comment]
* = missing from onestop mappings

Verified from analysis.asyc is in onestop mappings:

identification

**Comment by erinreeves** [comment]
add missing fields as "keyword" types.

**Comment by erinreeves** [comment]
Original finds of fields missing, off of master branch. Now branching off of 1238-dashboards

analysis_error_collectionIndex.json:
(not expected) parentIdentifierExists
endZoneSpecified
instantZoneSpecified

analysis_error_granuleIndex.json:
endZoneSpecified
instantZoneSpecified

**Comment by erinreeves** [comment]
On branch off of branch 1238-dashboards
