### ISSUE TITLE
Update accounts

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1288]
To reflect personnel changes

Update team passwords and access

- [x] slack
- [x] github
- [x] CU email account
- [x] help repo
- [ ] others?

## AC
Review https://github.com/cedardevs/help changes

**Comment by zebdelk** [comment]
Everything up to (and including) the github account in the help repo doc has been updated so far, and changes are available on the help repo.

**Comment by zebdelk** [comment]
Updated the last few non-sciapps specific passwords.
Created a story in the admin project to track sciapps specific passwords.
Last pending is an admin related role on the cedardevs gmail account, which requires waiting for security reasons.

**Comment by dneufeldcu** [comment]
Zeb: A few more account updates needed.

**Comment by zebdelk** [comment]
Everything I know about that needs to be updated is taken care of, except for a weird manager role on the gmail account. Need to make additional changes to pass a security check to be able to fix that.

**Comment by dneufeldcu** [comment]
Github is up to date
Slack is in progress
Ken to update account passwords and help repo

**Comment by kenhtanaka** [comment]
Zeb helped me get started. Will go through the list accessible via ansible-vault.

**Comment by kenhtanaka** [comment]
email password for outlooks seems to have changed with the gmail change.

**Comment by kenhtanaka** [comment]
Changed the rest of the passwords and checked in the file

**Comment by kenhtanaka** [comment]
Fixed URL and added instructions for connecting circleci to dockerhub

**Comment by erinreeves** [comment]
Updated readme a tad.
Ignore a few passwords that weren't changed as there are other security measures in place.
