### ISSUE TITLE
Geoplatform team support

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1298]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Geoplatform metadata manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       upload metadata into the data catalog more easily
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>streamline the process</td>
  </tr>
</table>

###Tasks
- [x] Provide samples and scripts to Geoplatform team

**Comment by ajakz** [comment]
Sent initial email with resources, so closing this.
