### ISSUE TITLE
Check if filter is already a saved search

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1314]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       see when Ive combined filters in such a way that they match what I already have in my saved searches 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>avoid making duplicates</td>
  </tr>
</table>

Right now the bookmark button fills in if you press it, but it does not fill in when you stumble upon a saved search (or even click into one of your saved searches).

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/commit/22feb70378f5ebdd20f20059c84898256486a330

**Comment by StrayCat1** [comment]
Didnt always work. Moved back into progress.

**Comment by zebdelk** [comment]
Reviewed
