### ISSUE TITLE
User API needs to meet JSON API spec

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1315]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop API developer and user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have the new Saved Search modules conform to the JSON API spec in the User API
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have predictable response payloads</td>
  </tr>
</table>

Controllers with responses to verify:
- [x] AdminController
- [x] SavedSearchController
- [x] UserController

**Comment by erinreeves** [comment]
Keep in mind about spring's @ControllerAdvice annotation that story 1316 may be using.

**Comment by erinreeves** [comment]
Adding tests to verify the return format is as expected per json api spec.

**Comment by erinreeves** [comment]
Concerned that the json api spec says the data resource returned should have an id and type, but our SavedSearch domain model has Id but not type...
https://jsonapi.org/format/#document-resource-objects

**Comment by erinreeves** [comment]
Almost wrapped up with SavedSearchController.
Working on the unit tests.
Had a discussion with Chris about how to handle the failed to authenticate cases. While spring should catch this before it hits the controller, via SecurityConfig file, we just want to be sure. So for now

**Comment by erinreeves** [comment]
On friday, Aug. 28th, after discussing with Chris I added setStatus to JsonApiSuccessfulResponse as well as that it takes an extra param HttpServletResponse so as to set that status to same thing.

**Comment by erinreeves** [comment]
Moved JsonApi* classes to data-common. Having some issues with tests failing on terminal but not in Intellij. Seems like dependency incompatibility.

**Comment by erinreeves** [comment]
Added tests to data-common JsonApi* classes.

**Comment by erinreeves** [comment]
Merged with branch 1184-userRest
