### ISSUE TITLE
User API controller advice

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1316]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have consistent error handling in the User API controllers
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have accurate and predictable HTTP status codes (particularly 4xx codes)</td>
  </tr>
</table>

**Comment by erinreeves** [comment]
Add spring's @ControllerAdvice and see if this fixes.
Used in the search api, customized it:
https://meet.google.com/linkredirect?authuser=1&dest=https%3A%2F%2Fgithub.com%2Fcedardevs%2Fonestop%2Fblob%2Ff26143a3c6090b707faff5f188d8a5dde8ce6212%2Fsearch%2Fsrc%2Fmain%2Fgroovy%2Forg%2Fcedar%2Fonestop%2Fapi%2Fsearch%2Fcontroller%2FGlobalDefaultExceptionHandler.groovy

**Comment by erinreeves** [comment]
https://www.baeldung.com/exception-handling-for-rest-with-spring/

**Comment by erinreeves** [comment]
Have controller advice for:
 resource not found exception and 
 access denied one

**Comment by erinreeves** [comment]
wrapping up tests.

**Comment by mcquinne** [comment]
Made the error handling controller advice a little more generic and merged it into the `userRest` branch.
