### ISSUE TITLE
Delete saved search from bookmark icon

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1321]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       delete (unsave/bookmark) a search from the result page (using the button with a bookmark icon)
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>unsave a search without having to navigate to the dashboard and find it</td>
  </tr>
</table>

**Comment by StrayCat1** [comment]
Things to think about - 
Should we also notify the user if the save/delete was not successful? If so, how? The red warning/error banner? 

Is this a potential vulnerability if people spam the bookmark button?

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/commit/22feb70378f5ebdd20f20059c84898256486a330

**Comment by zebdelk** [comment]
Reviewed
