### ISSUE TITLE
OWASP update

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1338]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>security engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       confirm vulnerabilities are addressed
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>ensure system security</td>
  </tr>
</table>

### Tasks
- [x] Address cve here: https://16526-62844166-gh.circle-artifacts.com/0/build/reports/dependency-check-report.html

**Comment by mcquinne** [comment]
Should be resolved by 14153735419b43b1754f69e7ed90333593a04282. Nightly build will run and confirm in a few hours.
