### ISSUE TITLE
Gitlab spike

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1341]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       compare the build process of gitlab to existing tools JIRA and CircleCI
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>determine if it is a better fit, simpler, lower cost</td>
  </tr>
</table>

### Tasks
- [ ] Experiment with mirroring github repo in gitlab and generating build artifacts with on premise solution.

**Comment by mcquinne** [comment]
Overtaken by #1346
