### ISSUE TITLE
Publish on-prem artifacts w/ GitLab CI

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#1346]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       publish deployment artifacts with gitlab
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>streamline the deployment process</td>
  </tr>
</table>

### Background
NCEI IT has made significant progress in implementing GitLab CI, which will give us much more control over the build process so that hopefully we can make build changes a little more rapidly. There is a (private) wiki page started with info about it here: https://confluence.ncei.noaa.gov/display/ITSS/Working+with+GitLab-CI

### Goals
- [x] Update the existing `.gitlab-ci.yml` file that we were playing with use the available images
- [x] Build all the executable jars
- [x] Execute all possible tests
    - [x] Avoid steps that require docker itself, i.e. some of the integration tests and the building of our own images
- [ ] Run OWASP checks
    - probably only on master?
- [x] Integrate sonarqube
- [ ] Publish the artifacts to the GitLab repository
    - with the maven plugin presumably?
    - client zip?

**Comment by mcquinne** [comment]
An example of a project publishing to gitlab's maven repo via gradle:
https://git.ncei.noaa.gov/dab/access-search-service/-/blob/gitlabci-containers/build.gradle

**Comment by dneufeldcu** [comment]
OBE new Jenkins
