### ISSUE TITLE
Finalize hiring process

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1357]
### Tasks

- [x] Phone screens
- [x] Code pairing exercise
- [x] Final interview with presentation

Job posting: [CIRES/NOAA NCEI Full Stack Software Developer](https://jobs.colorado.edu/jobs/JobDetail/CIRES-NOAA-NCEI-Full-Stack-Software-Developer/26568)

[CIRES Hiring Notes](https://docs.google.com/document/d/1whlUvVhU6FT4PmVA4YQMl1UrEXgQdCIlmSKxli07wnE/edit#)

**Comment by kenhtanaka** [comment]
21 Applicants
7 in the "Yes" category
14 in the "Maybe" category

6 phone screens completed.

**Comment by kenhtanaka** [comment]
The team reviewed the interview process and pair programming exercise.
