### ISSUE TITLE
Refactor UserAPI

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1363]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have separation of concerns
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>admin crud operations are distinct from user information for security</td>
  </tr>
</table>

### Goal
Separate out the generic, RESTful API endpoints supporting CRUD operations from those that are only for a logged-in user to retrieve their own data. This way each endpoint can be annotated with distinct security privileges.

#### Admin CRUD Endpoints

Endpoint | Verb | Action | Notes
---------|------|--------|------
/user | GET | Retrieve all rolesusers | Supports pagination
/user | POST | Create new user |
/user/{id} | PUT | Update user by id |
/user/{id} | DELETE | Delete user by id |

**Repeat basic REST pattern above for `/role`, `/privilege`, and `/saved-search`**

#### Logged-in User Endpoints

Endpoint | Verb | Action | Notes
---------|------|--------|------
/self | GET | Retrieve own profile |
/self | POST | Create own user | Used when first logging in
/self | PUT | Update own profile | Combine w/ POST, i.e. upsert?
/self | DELETE | Delete own user and associated data? | Should we support this?
/self/role | GET | Retrieve own roles |
/self/privilege | GET | Retrieve own privileges |
/self/saved-search | GET | Retrieve own saved searches | Supports pagination
/self/saved-search | POST | Create saved search associated w/ self
/self/saved-search/{id} | GET | Retrieve saved search by id and user self
/self/saved-search/{id} | PUT | Update saved search w/ given id and associated w/ self
/self/saved-search/{id} | DELETE | DELETE saved search w/ given id and associated w/ self

**Comment by mcquinne** [comment]
Work for this story was started in 456a7402

**Comment by mcquinne** [comment]
**Note** added some query param support for adding filters to list endpoints for several resources:

Endpoint | Filter params
----------|-------------
/saved-search | userId
/role | userId
/privilege | roleId, userId
