### ISSUE TITLE
Get python environment working

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1365]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      use python
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>write code and use ansible</td>
  </tr>
</table>

- [ ] Fix python environment on laptop

**Comment by erinreeves** [comment]
I got python 3 and ansible, whatever latest is as of yesterday.
