### ISSUE TITLE
Improve publishing of artifacts

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1375]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       publish artifacts to the environments we are currently using
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>streamline our CI/CD process</td>
  </tr>
</table>

### Tasks
- [ ] Refactor existing processes with more focus on cloud options

**Comment by mcquinne** [comment]
Running into several issues while building project w/ AWS CodeBuild:

1. Unable to fire up docker containers for integration tests
    
    - Ignore integration tests?
    - Privileged build?
2. Error related to character encoding default in Amazon Linux 2?
```
> Task :data-common:compileJava
/codebuild/output/src288735528/src/github.com/cedardevs/onestop/data-common/src/main/java/org/cedar/onestop/data/api/JsonApiError.java:123: error: unmappable character (0xE2) for encoding US-ASCII
     * A human-readable explanation specific to this occurrence of the problem. Like title, this field???s value can be localized.
```
3. Out of memory issue:
```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ca660000, 899284992, 0) failed; error='Not enough space' (errno=12)

#

# There is insufficient memory for the Java Runtime Environment to continue.

# Native memory allocation (mmap) failed to map 899284992 bytes for committing reserved memory.

# An error report file with more information is saved as:

# logs/hs_err_pid1.log
```

**Comment by dneufeldcu** [comment]
Use AWS ECR?

**Comment by dneufeldcu** [comment]
OBE let's revisit as needed.
