### ISSUE TITLE
Fix data-common toJson method/test

### ISSUE THREAD

**Issue by erinreeves** [cedardevs/onestop#1385]
The tests in data-common are failing, specifically the "toJson handles #situation as expected" in JsonUtilSpec is failing.

- [ ] Combine the two toJson methods (one takes an Object the other a Map) using something like this: if (obj == null || (obj instanceof Map && (Map)obj.isEmpty) { return "" }

If this doesn't work for some reason it is suggested to have the obj version return "" instead of null

**Comment by mcquinne** [comment]
Moving forward in priority to help support gitlab/aws builds
