### ISSUE TITLE
Archive cloud user interface 

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#1393]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>data manager / OSIM user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       upload a file (granule) to s3 along with the minimum viable metadata (parent id), have it archived based on usage, and have it show up in onestop down stream. 
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have a simple mechanism for archiving granules in the cloud and integrating with onestop</td>
  </tr>
</table>

This has a few steps- 
1) create a react app that uses the S3 API to upload an object 
2) secure that app with login
3) send metadata with that object so that it is associated with its collection
4) configure SNS/SQS so events are sent to the sqs-upload script using the onestop-python-client ( e.g. https://github.com/cedardevs/onestop-clients/blob/master/onestop-python-client/launch_e2e.py) 
5) confirm the object makes it to onestop

**Comment by StrayCat1** [comment]
https://main.d2my2s13uezpq6.amplifyapp.com/

Update: #1 and #2 are complete

Ran into some obstacles to get #3 working with our current react library solution. 

Then for the rest we will need to get access to an instance of Onestop where we can set up the rest of the workflow (be it NESDIS or our CEDAR org account).

**Comment by dneufeldcu** [comment]
Discussed will use cedar initially
