### ISSUE TITLE
Add CSV metadata extraction support

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1402]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>catalog and archive solution</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      extract additional metadata details of common file formats
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>improve the search and discover of file daa</td>
  </tr>
</table>

### Tasks
- [x] Add a spatial and temporal bounds extraction process to incoming csv data with lat/lon and time columns
- [x] Add the calculated spatial and temporal bounds to the IM JSON payload

### Description
Open the csv file from s3 bucket and find min, max values for lat, lon and date/time

**Comment by JeffreyHuynh1** [comment]
Can I assume that the csv files will always have the same format as the ones in the test files

**Comment by JeffreyHuynh1** [comment]
Does each csv contain one set of lon, lat, and date/time or will there be various lon, lat, and date/time in one csv?

**Comment by dneufeldcu** [comment]
Yes, the csv files will always be the same at this point in the process, and just one set of lat/lon/time values
