### ISSUE TITLE
Update and add readme for CSB data in BDP bucket

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1423]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a public user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       have an overview of the CSB data file format before accessing the data
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>be informed of how to access the data and use it</td>
  </tr>
</table>

### Tasks
- [x] Upload readme to BDP bucket

**Comment by kenhtanaka** [comment]
Updated the readme and documented changes to the CSV format. issued a pull request for 1283-on-prem-deployment to master. Uploaded new readme.html to s3://noaa-bathymetry-pds/readme.html

http://noaa-bathymetry-pds.s3.amazonaws.com/readme.html

**Comment by dneufeldcu** [comment]
Push up css
