### ISSUE TITLE
Reorganize content in developer/internal-practices doc

### ISSUE THREAD

**Issue by erinreeves** [cedardevs/onestop#1426]
After chatting with Brandon I've decided the developer/internal-practices docs is rather disheveled and doesn't have enough detail.

https://github.com/cedardevs/onestop/blob/1404-dev_docs_pass2/docs/developer/internal-practices.md

- [x] make sure mention of who's responsibility it is to merge a pull request (next step after a review is done).
- [x] Move tag and versioning to appropriate other doc

**Comment by kenhtanaka** [comment]
Reviewed and added a few changes. Checking back with Erin on my edits.
