### ISSUE TITLE
HTTPS Access for public objects

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1429]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>OneStop user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       download objects from the UI
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>work with the data locally</td>
  </tr>
</table>

### Tasks
- [ ] Review and confirm resource policy settings

**Comment by StrayCat1** [comment]
These public access settings
![Screen Shot 2020-12-31 at 12 02 52 PM](https://user-images.githubusercontent.com/26884996/103592148-7e4ab280-4eaf-11eb-9484-6ad59dc01984.png)

Plus this bucket policy- 
```
{
    "Version": "2012-10-17",
    "Id": "Policy1605737714816",
    "Statement": [
        {
            "Sid": "Stmt1605737712384",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::noaa-nccf-dev/public/*"
        }
    ]
}
```

Allow public access download via https

**Comment by StrayCat1** [comment]
Here is where we set that with boto - 
https://github.com/cedardevs/onestop-clients/blob/master/onestop-python-client/bucket_automation.py#L113
