### ISSUE TITLE
Update infraInstall.sh

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1431]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>devops engineer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       spin up the stack with skaffold dev
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>perform full stack testing</td>
  </tr>
</table>

## Tasks
- [ ] Update after troubleshooting

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/commit/95b42af52461b0ffb183dc59f1ab951615996f79
