### ISSUE TITLE
Onestop branch cleanup

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1436]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>team</td>
  </tr>
  <tr>
    <td><b>I want to </b></td>
    <td>
       isolate active branches and delete old unused brabches
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>not be distracted by old stale branches</td>
  </tr>
</table>

###

**Comment by mcquinne** [comment]
**Deleted the following fully-merged branches:**
1429-es-snapshot
1425-single-page-url-fix
1093-doc_internal_dev
1086-cartConfirmation
1385-toJsonFix
1084-public_user_api_docs_update
363-incorporate_help_docs_into_UI

**Comment by kenhtanaka** [comment]
Done
