### ISSUE TITLE
Avro Schema Validation 

### ISSUE THREAD

**Issue by JeffreyHuynh1** [cedardevs/onestop#1440]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>python client user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       validate avro schema
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>integrate into kafka work flow</td>
  </tr>
</table>

### Tasks
- [x] Look at different libraries for schema validation 
- [x] Integrate schema validation into onestop python client

**Comment by JeffreyHuynh1** [comment]
Avro Gen Library 
https://pypi.org/project/avro-gen/

- Creates concrete classes in order not to violate avro internals

**Comment by JeffreyHuynh1** [comment]
Avro Validator 
https://pypi.org/project/avro-validator/

- Library for python to provide validation of data against the schema

**Comment by JeffreyHuynh1** [comment]
Using Avro Validator library you can check if a schema matches your avro schema. However, the error is detected through terminal and will raise an exception in the traceback. The error will look something like 

Traceback (most recent call last):
  File "/Users/leonardo.almeida/.pyenv/versions/avro_validator_venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-7f3f77000f08>", line 18, in <module>
    parsed_schema = schema.parse()
  File "/opt/dwh/avro_validator/avro_validator/schema.py", line 28, in parse
    return RecordType.build(schema)
  File "/opt/dwh/avro_validator/avro_validator/avro_types.py", line 588, in build
    record_type.__fields = {field['name']: RecordTypeField.build(field) for field in json_repr['fields']}
  File "/opt/dwh/avro_validator/avro_validator/avro_types.py", line 588, in <dictcomp>
    record_type.__fields = {field['name']: RecordTypeField.build(field) for field in json_repr['fields']}
  File "/opt/dwh/avro_validator/avro_validator/avro_types.py", line 419, in build
    field.__type = cls.__build_field_type(json_repr)
  File "/opt/dwh/avro_validator/avro_validator/avro_types.py", line 401, in __build_field_type
    raise ValueError(f'Error parsing the field [{fields}]: {actual_error}')
ValueError: Error parsing the field [name]: The type [invalid_type] is not recognized by Avro

**Comment by JeffreyHuynh1** [comment]
When using pyavro-gen I had to adjust the avro files from "OperationType" ->  "org.cedar.schemas.avro.psi.OperationType" otherwise it wouldn't recognize the dependency. Had to do this for all avro files with dependencies.

**Comment by JeffreyHuynh1** [comment]
Classes generated from pyavro-gen contains incorrect syntax for import statements, have to update this manually on all files

**Comment by JeffreyHuynh1** [comment]
When serializing the classes to JSON, the enum class types were throwing errors. Fixed it with 'json.dumps(enum_obj, default=str)'

**Comment by JeffreyHuynh1** [comment]
Code to generate avro classes 

generator = pyavro_gen.generator.AvroGenerator(
    AvroPaths(
      input_path='psiSchemas/',
      output_path='schemas.psiSchemaClasses/',
      input_schema_file_extension='avsc',
      base_namespace='org.cedar.schemas.avro.psi'
    )
  )
  generator.process()

- Had to run this twice, due to the two different namespaces
 -- 'org.cedar.schemas.avro.psi'
 -- 'org.cedar.schemas.avro.geojson'

**Comment by erinreeves** [comment]
https://github.com/cedardevs/onestop-clients/pull/47

**Comment by erinreeves** [comment]
To execute script:
python launch_e2e.py -conf config/aws-util-config-dev.yml -cred config/credentials-template.yml

**Comment by erinreeves** [comment]
Getting exception in S3Utils trying to do s3object.metadata.

Also sometimes OneStop stack starts not digesting messages and noticed this error, which didn't seem to recover after a minute so had to restart OneStop:
[onestop-registry-0 onestop-registry] org.apache.kafka.common.errors.DisconnectException: null
[onestop-registry-0 onestop-registry] 
[onestop-client-859d4688c-mbnr2 onestop-
