### ISSUE TITLE
Set NWS/URMA write permissions for Mark

### ISSUE THREAD

**Issue by kenhtanaka** [cedardevs/onestop#1455]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Mark Capece</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       write to the nesdis-nccf-staging/public/NWS/URMA folder
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>place my data files there</td>
  </tr>
</table>

- [ ] Set permissions for Mark

**Comment by dneufeldcu** [comment]
Duplicate see #1459
