### ISSUE TITLE
Give NCEI DAB write privileges to URMA

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1459]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>URMA developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       land files from my FTP process to the URMA s3 bucket
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>integrate with OSIM</td>
  </tr>
</table>

- [ ] Grant rw privileges to s3://nesdis-nccf-staging/public/NWS/URMA/ to DAB developer

**Comment by geoneubie** [comment]
Confirmed by Mark C. in DAB

**Comment by erinreeves** [comment]
Per Dave: oh that's done, it was for a guy in Asheville he tested and it worked yesterday
