### ISSUE TITLE
Script to clear S3 bucket

### ISSUE THREAD

**Issue by kenhtanaka** [cedardevs/onestop#1478]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       run a script to clear the S3 bucket "archive-testing-demo"
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have a non UI way to quickly prepare the destination bucket for receiving files, typically done during a demo to show SNS and SQS messages initiated by file activity in S3</td>
  </tr>
</table>

**Comment by kenhtanaka** [comment]
Added a pull request for the 1478-clear-bucket branch of osim-deployment

https://github.com/cedardevs/osim-deployment/pull/4

**Comment by erinreeves** [comment]
Looks good
