### ISSUE TITLE
Tag 1.1 release

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#150]
- [x] Release tagged
- [ ] LanDesk ticket submitted

**Comment by ajakz** [comment]
https://github.com/cedardevs/onestop/releases/tag/v1.1.0

**Comment by dneufeldcu** [comment]
https://github.com/cedardevs/onestop/releases/tag/v1.1.1

**Comment by dneufeldcu** [comment]
Waiting on JB to proxy api/info on test before submitting security ticket.
