### ISSUE TITLE
Merge patch

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#1506]
Some changes were lost when branch 49-enum-classes was merged to master.

Specifically, some initial steps in removing file based config were lost in WebPublisher.py (see init method)

Likewise s3_notification_handler checked for a config file passed in as a parameter and if not found assumed credentials were available as environment variables from helm pod installation (secrets)

The PR reverts back those changes.
https://github.com/cedardevs/onestop-clients/pull/54

**Comment by erinreeves** [comment]
Merged pull request 5 that correlates to this.
