### ISSUE TITLE
Landing page updates

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#152]
- [x] Change label under the NOAA Data Catalog, please use "NOAA Data Catalog" instead of "Dataset Search." 
- [x] Rename page datasetsearch.html
- [x] Change text from

'Welcome To The NOAA Data Catalog Search Portal
Search functionality of the NOAA data catalog is under construction. Access to the original data set catalog site will remain available while we continue to make progress on our new data discovery portal, OneStop.'

To:

'Welcome to the NOAA Data Discovery Portal
We are developing and testing two approaches to enable searching NOAA's vast data holdings: a traditional catalog for all data, and enhanced searching for selected datasets.'

**Comment by aaronjcaldwell** [comment]
Different repo but changes can be found here: https://github.com/cedardevs/data.noaa.gov-landing/commit/e8b9b4ffde785605b1a9f81fb0589febcd95e814
