### ISSUE TITLE
Wiki page documentation with request/response examples for search API

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#154]
AC: Documented examples are available for search by:
- [x]  text
- [x]  spatial bounds
- [x] time

**Comment by ajakz** [comment]
Wiki page: https://github.com/cedardevs/onestop/wiki/OneStop-Search-API

FYI I added some of the query help tips found on the UI to the page since they're relevant here. Also removed "sort" entirely from our request schema since it wasn't actually doing anything.
