### ISSUE TITLE
Facets hierarchy

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#17]
Fix GCMD keyword display to a hierarchical view, defaulting to L0 and L1 keywords auto-displayed (user can dive down further). No limitations on how many levels can be expanded within the keywords menu. Part of this work would be migrating the current facet sub-menus underneath a Keywords one; Temporal and Spatial to be added later.

AKA: "Amazon style."

**Comment by zebdelk** [comment]
Closed by #271
