### ISSUE TITLE
Tag a release 1.2.1

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#173]
...Incorporating issue #170 because, like, it's a pretty big deal.

**Comment by zebdelk** [comment]
Make note of specific steps used if done before #183, to make sure that automating the release more completely includes everything needed.

Alternatively,  if #183 is complete first, use this as a test to confirm it did everything.

**Comment by ajakz** [comment]
Push to release/1.x and tag from here

**Comment by dneufeldcu** [comment]
Because it's proper.
