### ISSUE TITLE
Migrate OneStop to use CedarDevs artifactory instead of CIRES-NCEI.

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#181]
OneStop is still publishing artifacts to the old organization name. The Cedar org should add a bintray repository for OneStop and the build should be migrated to push to the correct location.

**Comment by zebdelk** [comment]
1. I added code to build.gradle for the api-search, api-metadata, and client modules in the feature/elasticsearch branch.
1. I have a branch (cedar-package) that branches from the 1.2.1 deployment tag and adds the source code module to api and client modules on the master branch.

What needs to be reviewed:
1. [ ] Does the content of the source jars look correct?
1. [ ] Should the new maven repo actually have the 1.2.1 artifact, or should we delete it and only use it going forward from the ES 5.x?
1. [ ] Should we keep the changes in the cedar-package branch, or do we need them? (I'm currently thinking we could just delete that branch).
1. [ ] Make sure Zeb deletes the test artifacts from JFrog and BinTray, as well as any test tags still lingering in the repo.

**Comment by mcquinne** [comment]
Dropped the cedar-package branch as the source jar changes had already been added to the feature/elasticsearch branch and are therefore now on master.
