### ISSUE TITLE
Enhance Promotion Script to create Release

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#183]
The promotion script should call the github api to create the release to go along with new tags and artifacts. This will help automatically tie the entire release process together.

 - [ ]  Replace the script with an interactive python script to prompt for the needed input and provide current status info, based on the new deployment script on the federal system
 - [ ]  Prompt for release notes in addition to version
 - [ ]  Verify that a tag is not already in use
 - [ ]  Create a release based off the new tag. Mark as pre-release or latest-release as needed.
 - [ ]  Update Internal-Development-Practices on the OneStop wiki to reflect correct usage and release requirements.
 - [ ]  use github api to automate release branching requirements as well

**Comment by mcquinne** [comment]
Alternative approach: Use the travis [github releases](https://docs.travis-ci.com/user/deployment/releases/) deployer to do the github api part for us.

**Comment by StrayCat1** [comment]
This is old, closing it in favor of #896  and #944
