### ISSUE TITLE
Fix gcmd keyword mappings in MetadataParser

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#188]
Changes to how ES 5 maps strings makes for an awkward handling of our GCMD keywords. In order to use the path hierarchy tokenizer, the field has to be of type text... but aggregations won't work on text fields, only keyword type, unless we enable a questionable memory setting. In lieu of making bad but easier decisions, we should tokenize the keywords ourselves on ingest. 

See [GCMD keyword structure](https://earthdata.nasa.gov/about/gcmd/global-change-master-directory-gcmd-keywords) (at bottom)

AC:
- [x] Tokenize science & location GCMD keywords in MetadataParser; all other keywords leave as-is (for reference, integration test data is in correct format for tokenized gcmd keywords)
- [x] Put text version of GCMD keywords into Keywords field

------------------------------------------

This is maintaining the original way in which gcmd keywords were indexed and is simply ensuring we continue to index them as usual.

**Comment by mcquinne** [comment]
Did some clean up, looks good now.
