### ISSUE TITLE
Reevaluate field boosts

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#190]
This really has no value in being done before we've finished updating mappings. This should be done as part of wrapping up the Mappings epic and starting the Search Optimization epic. The steps to be followed, where **this issue is the last step**:
- [x] Consider building flattened granules within the Search index only using a new ETL job?
- [ ] **Reevaluate field boosts once Search index is finalized**

------------------------------------------------

Our mapping could use another pass for usefulness, search optimization, and potential extra aggregations (like the acquisition elements). Changes will be reflected in json mapping files, MetadataParser, SearchIndexService/SearchRequestParser, and default field boosts in application.yml. 

Things to think about...
- Should `gcmd` fields also be searchable AND boosted along with `keywords` when `gcmd` keywords are copied into `keywords`? 
- ~Making `acquisition` elements more searchable/adding them to `keywords`~ (will be done as part of #244)

**Comment by mcquinne** [comment]
We'd rather not *search* against gcmd fields since their values are also represented as keywords, but we still need to be able to support aggregation for keyword filtering.

**Comment by forgo** [comment]
add extra fields to generic keywords

**Comment by zebdelk** [comment]
We might want to re-evaluate our mappings at this point, with PSI in mind.

**Comment by zebdelk** [comment]
Clarification on fields we search: currently we search against all. We should consider just using title, description, and 1-2 other? (This is probably the discussion we need to have to decide what should change)

**Comment by dneufeldcu** [comment]
Will be covered by #1147
