### ISSUE TITLE
Enable SSL connection to ES

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#197]
Support under ES 5.0

**Comment by dneufeldcu** [comment]
Stalled need help with certificate issues.  Open ES support ticket.

**Comment by mcquinne** [comment]
SSL can now be used with our API application's by configuring elasticsearch.ssl.enabled = true. We're assuming that the SSL context of the JVM running the apps is configured correctly to talk to elasticsearch. We will verify that this approach works by testing it on NCEI's infrastructure.

**Comment by zebdelk** [comment]
reviewing https://github.com/cedardevs/onestop/commit/6350b30233eef2debd27f9f07b8dfe922acfacef

**Comment by zebdelk** [comment]
review conclusion: looks good!
