### ISSUE TITLE
Document Indexed Fields

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#202]
The metadata team has asked us to document which fields from the metadata are being indexed. The goal is to line them up with the fields the metadata team is calling required or recommended for onestop metadata. Also it will help the analysis of existing "thick clients" to determine if onestop can support their querying needs.

Once we've done this, we should compare with the metadata team's required fields and generate any follow-on stories for fields that we aren't indexing and should be.

**Comment by ajakz** [comment]
Fields are documented on our wiki here: https://github.com/cedardevs/onestop/wiki/Metadata-Indexing-Details

We should point the metadata team to this page after someone has verified all fields have been accounted for and the page is good to go.

**Comment by ajakz** [comment]
FYI Li sent WOD collection & granule metadata records with some new fields to index via email. This XML may also have ISO hierarchy in place.

**Comment by zebdelk** [comment]
Starting review.

**Comment by zebdelk** [comment]
Looks good. If someone needs more detail about the fields comprised of sub elements or anything, hopefully it's because they're building a thin client and are talking to us. This should be a good starting point for anyone investigating query needs.

**Comment by zebdelk** [comment]
Arianna emailed this to the metadata group. We'll generate stories as needed.
