### ISSUE TITLE
Disable automatic mapping in ES indices

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#220]
See [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation) -- "Automatic mapping creation can be disabled by setting index.mapper.dynamic to false per-index as an index setting." 

We should set this in the mappings of both indices so as to prevent extra fields, incorrectly mapped fields, etc. from happening.

**Comment by ajakz** [comment]
The correct setting to accomplish this is actually setting "dynamic" to "strict" on the type mappings (see [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html)). What I linked to in the description is ES mapping new fields to certain types -- which if we don't accept new fields, won't happen.

**Comment by zebdelk** [comment]
Reviewed!
