### ISSUE TITLE
Investigate handling date search for paleo

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#223]
Paleo dates don't fit with our traditional calendar search options.  We need to investigate and document an approach using a sample metadata record from paleo.

<gml:TimePeriod gml:id="datasetTimePeriod">
  <gml:description>Begin date: 39450 cal yr BP, -37500 AD; End date: -50 cal yr BP, 2000 AD</gml:description>
  <gml:beginPosition>-37500</gml:beginPosition>
  <gml:endPosition>2000</gml:endPosition>
</gml:TimePeriod>

Full record: https://drive.google.com/a/noaa.gov/file/d/0BxaVtlmPt2jIVnRSUVZiVlF4Rk45Y0tnQVl0azkwYVYyRmln/view?usp=sharing

**Comment by ajakz** [comment]
Add startYear and endYear values to ES mapping -- search by this numerical field by an additional option in the Time filter menu.

**Comment by ajakz** [comment]
Some handy links:

- [Paleo metadata WAF](https://www1.ncdc.noaa.gov/pub/data/metadata/test/paleo/iso/xml/)
- [Paleo search page](https://www.ncdc.noaa.gov/paleo-search/) (UI example for date search)

**Comment by zebdelk** [comment]
We reviewed this as part of #494.
