### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#224]
Replace ETL module with a tar of collection and granule data (more than the existing tar, which has insufficient granules for local/cu server testing)

**Comment by zebdelk** [comment]
- [ ] Update checklist template with specifics based on test data
- [ ] include dev test data for edge cases

**Comment by ajakz** [comment]
The testData tar file is located on Google Drive under OneStop/Testing. I put a date on it (20171108) just so we are able to keep track of what these are, since it's probably a good assumption that we may add more edge case records in the future.

**Comment by ajakz** [comment]
Newer file available in same location -- 20171114

**Comment by mcquinne** [comment]
Added the most recent test tarball to the ansible playbooks for sciapps deployment and did a full reload so the sciapps system now contains the exact metadata from the tarball. Think we're in good shape on this front for now.
