### ISSUE TITLE
data.noaa.gov landing page updates

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#231]
Remote libraries (css) need to be brought in as local content.

External links to libraries hosted on non-approved third party CDNs need to be brought in locally to the application:
https://unpkg.com/purecss@0.6.2/build/pure-min.css
https://unpkg.com/purecss@0.6.2/build/grids-responsive-min.css

HTML for the landing page is here:
https://github.com/cedardevs/data.noaa.gov-landing

**Comment by zebdelk** [comment]
Repo: data.noaa.gov landing page - move css into here

**Comment by ajakz** [comment]
Yep!
