### ISSUE TITLE
Keywords + acquisition info changes

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#244]
Split from #188 since we've always had GCMD keywords tokenized, and that is not really part of improving mappings to maintain that feature.

Improve usability of acquisition elements and topicCategories by fixing how they're indexed in ES:

- [ ] Consolidate `topicCategories` into `keywords`...? Might be an issue with GeoPortal using our indices if we do this though (need to verify)
- [ ] Tokenize on ingest for `acquisitionInstruments.instrumentIdentifier`, `acquisitionPlatforms.platformIdentifier` too (put in keywords?)
- [ ] If moving acquisition elements to keywords, need to fix test data in api-search module integration tests

**Comment by mcquinne** [comment]
We may be able to postpone this work as long as we parse enough information into our staging index as a result of #414

**Comment by ajakz** [comment]
Closing in favor of #473. There is not yet a clearly defined path forward for making acquisition info more useful in search; regardless, the Mappings epic concerns filling up Staging as much as possible. This is work that can (and should) be done much later, but it needs a clearer plan than what's laid out in this issue.
