### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#245]
We need to have a testing walk-through script that we run through prior to publishing a release. This should run through the features of the entire OneStop system (API + UI), verifying all major functionality works as expected.

**Comment by zebdelk** [comment]
Do this as part of the 2.x release.

**Comment by zebdelk** [comment]
- [ ] Use chrome devtools mobile view to check how it looks on devices.

**Comment by dneufeldcu** [comment]
Draft checklist started here:
https://docs.google.com/document/d/1bkCcn_xWTXU5WjDrrcBtpaV8Qmcjn5XpDAzC3te8sLs/edit

**Comment by dneufeldcu** [comment]
AC: 
- [ ] A template release checklist that gets converted to a github issue.

**Comment by zebdelk** [comment]
Here's my first pass at a template: https://github.com/cedardevs/onestop/wiki/Release-Checklist

Some assumptions I made:
- That the updated jar of test data to populate with with contain the same (or similar) data to running our current ETL DEM and CO-OPS
- That we will continue to flesh out the edge case section, particularly as we develop test data for that in #224
- We can add tests to do in the 508 section as we improve accessibility of the main search components
