### ISSUE TITLE
Second pass analytics

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#248]
- [ ] Add local with UA ref from web team

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
    ga('create', 'UA-108560292-1', 'data.noaa.gov');
    ga('set', 'anonymizeIp', true);
    ga('send', 'pageview');
    </script>

**Comment by dneufeldcu** [comment]
Note in theory a new UA-##### specific to data.noaa.gov and OneStop *may* be in the works.  I've asked for an update, and we'll go with defaults above until we hear differently.

**Comment by dneufeldcu** [comment]
New UA value received and story updated.

**Comment by zebdelk** [comment]
reviewing
