### ISSUE TITLE
MediaCurrent: Make result cards stand out more

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#253]
TBD how we do this...

**Comment by zebdelk** [comment]
Short experiments with colors to make borders pop.

**Comment by zebdelk** [comment]
https://docs.google.com/presentation/d/1CIjXWMk-9D0Ku8if01fzpi7juMUUrSRBw1rk4EhqcQc/edit#slide=id.g28cb786944_0_37

**Comment by zebdelk** [comment]
Review:

- [ ] Team member feedback / questions on above slides.

**Comment by zebdelk** [comment]
Short team meeting presenting slides.
Conclusions:
- faded background looks good, but cards are too dark now
- simplifying the 508 view with a solid background is better

Changes:
- [ ] 508 search and results page: solid background - try dark blue
- [ ] main search results: reduce left shadow fade so the card is not too dark
- [ ] main search results: look for an easy way to reduce padding on the left and right sides. (The grid view needs to be refactored, so if we can't easily tweak this we'll revisit it when we update those components).

AC/Review:
- [ ] Pull request to commit code to master
- [ ] MediaCurrent is invited to the next Sprint Review / demo - we will show them the changes then.

**Comment by zebdelk** [comment]
Because of the structure of resultsLayout, it's not a good idea to mess with the padding and margins in there right now. There is not an easy way to reduce padding on the left or right sides.

**Comment by zebdelk** [comment]
Here are screenshots of how my current code looks:

![Screen Shot 2017-10-19 at 11.46.06 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455fa6b7191a379ee0c2f57415f48bc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94956a1113261e476336e0a.png)
![Screen Shot 2017-10-19 at 11.46.11 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455fa6b7191a379ee0c2f57415e4fbc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94956a1113261e77e336e0a.png)
![Screen Shot 2017-10-19 at 11.46.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455fa6b7191a379ee0c2f57415e4bbc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb29842c259f34be94956a1113262ee74336e0a.png)
![Screen Shot 2017-10-19 at 11.46.20 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455fa6b7191a379ee0c2f57415d4ebc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94956a1113261e673336e0a.png)

**Comment by dneufeldcu** [comment]
This all looks really good.  One request would be to shift the text and shadow on the result cards towards the top of the card.  While it's much more readable it's covering more of the image than I like.

**Comment by ajakz** [comment]
Title and shadow shifted a smidgen:
<img width="754" alt="screen shot 2017-10-20 at 2 54 08 pm" src="https://user-images.githubusercontent.com/5514537/31841403-942e1862-b5a6-11e7-9fe4-d93e40dc8c2b.png">

Interestingly, the shadow and title were originally in the same place, it's just more pronounced that it's covering the image after Zeb's work. _Smells like success!_
