### ISSUE TITLE
Add Accessibility Statement

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#264]
Add the following text to the bottom on the 508 site page: 

'Accessibility Statement NOAA OneStop is committed to providing access to all individuals who are seeking information from our website. We strive to meet or exceed requirements of Section 508 of the Rehabilitation Act, as amended
in 1998. We recognize not all pages on our site are fully accessible at this time, however our accessible site aims to meet Level AA accessibility and provides users with access to all of the same datasets. We will continue to make improvements across our entire site until all pages are fully compliant. If you experience any challenges while accessing parts of our site, please contact ncei.info@noaa.gov'
[NOAA OneStop- Accessibility Statement.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591ccb952fa3730020d900a6/125516c66e82c728ace21e0d46c6bbbb02c2aca78adaab4cb410b0b52a4522603a0da1227c8cf731ff716f001b0a13f91f1c4d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb29842c259f34be94f50a1143763e671326e0a.pdf)

**Comment by forgo** [comment]
Change statement background color / text color, link color, or both to make more readable.

**Comment by zebdelk** [comment]
Updated link color in: https://github.com/cedardevs/onestop/commit/0ef5e5ddefe80340cae578d1a0b323ae1ec6764e
