### ISSUE TITLE
Backslash \ should be handled on UI search.

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#278]
Note: Original story's context considered the regex search ability given to us by ElasticSearch. This regex query is not implemented in API-Search however. There was confusion over REGEX vs the query_string's allowed wildcard and escaped character search. OneStop currently does not implement REGEX searches so this story has been modified to work on just client side validation of queries that involve a backslash.

When a user uses OneStop's search, and enter's a `\` that is not followed by another reserved character, API-Search receives an invalid query and returns a 400 response. A user should be able to receive UI notification that the query is incorrect.
- [ ] UI notifies user of malformed query using `\`

**Comment by rongxanh88** [comment]
After doing lots of research and working through code, I decided that this should not be fixed. The regex required for helping the user with the queries would be quite complicated. Mainly the only thing we can solve here is if the user uses one backslash to escape a beginning quote or opening bracket, without using one for an ending bracket or quote.

However, elastic search is smart enough to use those escaped characters without the use of a backslash, so `()` and `{}` and `""` will work fine without escaping them.

**Comment by rongxanh88** [comment]
Also, to use a regex, everything must be put into double quotes so that the regex field is interpreted literally like `"/regex/"`.

Otherwise, if not using double quotes, every reserved character must be escaped.
Example: `\/\^GHRSST\/`
