### ISSUE TITLE
Collection result bugs

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#283]
- why isn't it loading the images? (check data being loaded from metadata tar)

**Comment by dneufeldcu** [comment]
Looking at GHRSST collections we are seeing:
thumbnail:""
aka no URL in ES, trace back to metadata or possible load issue?

**Comment by zebdelk** [comment]
Note: there have been some weird things going on with the CU server due to the index prefix name. We should wait until we've redeployed, because this may be a side effect of that problem.

**Comment by zebdelk** [comment]
It looks like the problems were resolved by resetting the deployment and reloading the data, combined with fixing a display bug on the maps.
