### ISSUE TITLE
Cleanup 2.0.1 artifacts

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#288]
- delete docker images labeled with 2.0.1
- check fjrog artifactory / bintray
- make sure there are no remaining 2.0.1 tags in the github repo

There should only be snapshots, no releases, so the only place I would expect to see stuff to clean up anything is the docker images on hub.docker.com, but it's worth verifying there are no other linginger artifacts that won't be cleaned up automatically.

**Comment by ajakz** [comment]
@zebdelk is this relevant anymore?
