### ISSUE TITLE
Google Analytics Done Right

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#290]
Currently we have the fed GA stuff hardcoded into the client, which poses some fairly obvious problems. We should enable GA on the client to handle two scenarios: don't happen at all (dev work), custom property ID (UA string) & tracking settings. 

GA is currently initialized in the index.jsx file but could be run elsewhere. The html-webpack-template plugin was a good start until it became evident that you can't adjust any settings through it. Plus, it's not configurable to insert GA via webpack without rebuilding artifacts.

AC:
- [ ] Config options for property ID & tracking settings (possibly another use for the info endpoint in our API)
- [ ] Depending on build profile use appropriate ID

Bonus:
- [ ] Setup GA as outlined by Mediacurrent for CU servers

**Comment by dneufeldcu** [comment]
Chris working on configuring analytics id into search-api like via yml for example
