### ISSUE TITLE
Apply UI changes to 1.3

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#292]
Changes on master under the client directory need to be applied to the 1.3 branch.

**Comment by zebdelk** [comment]
The easiest way to do this is:
1. checkout release/1.x
1. `git checkout master -- client` to check out just the module which has changed.

**Comment by zebdelk** [comment]
The main commit taking care of this is ffb0f36. We will have to merge the latest changes when we've wrapped up work for client.

**Comment by mcquinne** [comment]
Changes applied, 1.3.0 released
