### ISSUE TITLE
Spatial rendering across dateline in matching files (granules) view

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#296]
Rendering elements across the dateline in the same view as other points (see COOPS granule view) causes polygons that cross the dateline to render in a different view than points -- so one has to scroll the map one full revolution over in order to see the other elements. We should look into stitching two polygons together at the dateline instead of translating coordinates so that map.fitBounds() renders correctly and all elements appear on screen together.

**Comment by dneufeldcu** [comment]
Moving this backlog; not sure of the value proposition let's discuss.

**Comment by ajakz** [comment]
Removing from Spatial Filter epic since this doesn't have anything to do with the filter. This bug still exists and is still frustrating but the solution may be to ensure all drawn points and polygons are converted to [0, 360] from the given [-180, 180] range. 

**It's possible that some of the work done in geoUtils for the filter work can be utilized here -- stitching polygons together is likely not necessary.**

**Comment by zebdelk** [comment]
This bug may be invalid after changes in #440

**Comment by ajakz** [comment]
The granule results view will no longer have this map component; issue no longer applies
