### ISSUE TITLE
SPIKE: ArcGIS API react

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#305]
Check it to see if it's better than leaflet?

https://developers.arcgis.com/javascript/latest/sample-code/widgets-frameworks-react/index.html

- [x] Is 4.x still using DOJO? yes
- [x] Is it better than leaflet? probably not, using old map with some cleanup for now, will address the progress made toward ArcGIS and feasibility later

**Comment by dneufeldcu** [comment]
AC: TimeBox to 5 days; Write-up results for review by team.

**Comment by forgo** [comment]
A majority of work was made to getting an equivalent map from leaflet into ArcGIS with a react wrapper. Unfortunately, keeping the map in sync with the new left menu location form proved difficult with this wrapper.

There are other React/ArcGIS wrapper options out there, but they don't appear to be official-official, and we should move forward with existing functionality. If we do find a viable wrapper for React/ArcGIS, then there is a lot of good work already done to get us most of the way (with the exception of being able to draw dynamically with the DOJO/React cluster).

**Comment by mcquinne** [comment]
End result: We're sticking with Leaflet for now to avoid pulling in all of the dojo/arcgis dependencies, plus they didn't really seem to solve our problems anyways.
