### ISSUE TITLE
Footer fix

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#317]
NOAA.gov hasn't implemented HTTPS. This means our relative protocols fail when running on a server using HTTPS (which we do). So the following footer links need to force use of HTTP.
- [x] Freedom of Information Act 
- [x] Information Quality 
- [x] Disclaimer

**Comment by mcquinne** [comment]
Found another instance:

- [ ] NOAA logo in top left

**Comment by zebdelk** [comment]
Reviewed!
