### ISSUE TITLE
Support for video granule links

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#318]
If a collection's granules have links to video -- namely YouTube -- have a toggled extra tab to embed video in.

**Comment by forgo** [comment]
TODO:
- [ ] provide real links into the array for the VideoView component
- [ ] style clickable/expandable headings for videos

**Comment by ajakz** [comment]
Latest tar in Testing directory on Google Drive has a SUVI record with video links

**Comment by ajakz** [comment]
Latest tar in Testing directory on Google Drive has a SUVI record with video links

**Comment by mcquinne** [comment]
This issue appears to have been superseded by #319
