### ISSUE TITLE
Tag 1.3.2 release of onestop

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#321]

**Comment by mcquinne** [comment]
Release candidate is up and running on sciapps with fully-reloaded data. Here's the release checklist!

## Manual UI checks

### Set up the test environment

- [ ] Deploy the latest candidate to the SciApps demo site
- [ ] Reset the indices and reload the data.

### General checks

- [ ] Verify CSS changes work across browsers
  - [ ] IE 11 on AdminLan
  - [ ] Firefox latest
    - [ ] on Mac
    - [ ] on AdminLan
  - [ ] Chrome Latest
    - [ ] on Mac
    - [ ] on AdminLan
  - [ ] Safari
  - [ ] Opera
  - [ ] Confirm supported browser docs: [Supported Browsers](https://github.com/cedardevs/onestop/wiki/OneStop-Client-Supported-Browsers)
- [ ] Use chrome devtools mobile view to check how it looks on devices.
  - rotate to landscape views
- [ ] Landing page functionality
  - [ ] Summary lists expected number of collections (413) and granules (51)
  - [ ] Correct Version #
  - [ ] Links in the header menu and footer work
- [ ] General page responsiveness (adjust window size between large and small)
  - [ ] Does landing page adjust gracefully?
  - [ ] Do header links collapse to hamburger menu on small window? 
  - [ ] Do header and footer elements stay contained within their respective parent? 
  - [ ] If all keyword categories are expanded on search page, do they stay visible (push footer down)? 
  - [ ] Do result cards respond to page adjustments? 
  - [ ] Does an open collection detail view realign elements cleanly on each tab?

### Search Verification

#### Keywords

  - [ ] From landing page, click 'Weather' in Search By Topic. Results count is 53. Confirm clicking `Show More Results` button loads 20 additional results, after 2 clicks button disappears and section header states 'Search Results (showing 53 of 53)'
  - [ ] All cards show thumbnail images or black overlay in event image is slow to load/not available (external service; either of these are okay)
  - [ ] Keywords Data Theme shows:
    - Agriculture (1)
    - Atmosphere (15)
    - Biological Classification (1)
    - Biosphere (1)
    - Climate Indicators (1)
    - Cryosphere (1)
    - Oceans (51)
    - Spectral/Engineering (1)
  - [ ] Confirm keyword labels are rendered and functioning accurately:
    - Drill down through Data Theme, verifying labels match 'Atmosphere' > 'Atmospheric Winds' > 'Surface Winds' > 'U/V Wind Components'.
    - Select keyword above. Tag above collection cards reads 'U/V Wind Components'.
    - Open collection card. Verify tag appears as 'U/V Wind Components' in 'Themes' section.
    - Back to Keywords, confirm 'Anemometers' and 'MOCNESS Plankton Net' under 'Instruments' category.
    - Select both in facet menu. Confirm string format is consistent in tags.
    - Open collection card and confirm format again under 'Instruments' category.
    - Look for last `search` request in browser dev tools. Confirm request payload is: 
{"queries":[{"type":"queryText","value":"weather"}],"filters":[{"type":"facet","name":"science","values":["Atmosphere > Atmospheric Winds > Surface Winds > U/V Wind Components"]},{"type":"facet","name":"instruments","values":["ANEMOMETERS","MOCNESS > MOCNESS Plankton Net"]}],"facets":true,"page":{"max":20,"offset":0}}

#### Temporal

- [ ] Overlapping Allowed
    - Start with a fresh search by selecting 'Fisheries' topic on Landing Page -- 2 results returned
    - In time filter, select start as any day in 2010, apply to search and hit magnifying glass button to initiate new search -- now 1 result, 'Tutuila, American Samoa [...]' (AKA Return data covering anytime after {day}, 2010)
    - Clear time filter (X button) and initiate new search again -- back to 2 results
    - Apply new time filter by selecting end as any day in 1990 and initiate new search -- 1 result, 'Tutuila, American Samoa [...]' (AKA Return data covering anytime before {day}, 1990)
- [ ] Overlapping Restricted
    - TBD
- [ ] Paleo Dates
    - TBD

#### Spatial

- [ ] Rendering across dateline
    - Search `"southern alaska coastal relief"` -- 1 result returned. 
    - Inside collection summary tab, bounding coordinates read: 'Bounding box covering 170°, 48.5°, -130°, 66.5° (W, N, E, S).' 
    - Map image shows enclosed area of Alaska.
- [ ] Rendering across prime meridian
    - Search `mediterranean` -- 17 results returned.
    - Open GHRSST ODYSSEA collection (should be second result). Bounding coordinates read: 'Bounding box covering -18.5°, 30°, 36.5°, 46.5° (W, N, E, S).'
    - Map image shows enclosed area of Mediterranean region in Europe.
- [ ] Searching by geometry
    - Search `water` -- 393 results returned.
    - Using map filter, draw a bounding box over the Mediterranean region and initiate new search -- 64 results returned.
    - Apply 'Exclude Global' filter -- TBD results returned (need to reinstate this filter in the coming Spatial filter section)

#### Collection View

- [ ] Confirm title expands/collapses

Summary Tab
- [ ] Time range
- [ ] No end date 
- [ ] No time range
- [ ] Spatial -- bounding box
- [ ] Spatial -- point (search `glacier`)
- [ ] Spatial -- no geometry
- [ ] DSMM present
- [ ] DSMM not available
- [ ] Keywords

Description Tab
- [ ] Thumbnail image
- [ ] No thumbnail image but spatial bounding available
- [ ] No thumbnail or spatial bounding
- [ ] Description 

Matching Files Tab
- [ ] Map rendering
- [ ] Data types

Access Tab
- [ ] TBD

Citation Tab
- [ ] TBD

#### Miscellaneous Edge Cases

- [ ] Results with no thumbnail image show a map
    - Search `Nikolski`. Returns 4 results, 2 of which have no thumbnail image and should instead render a map.
- [ ] Results with no spatial bounding & no thumbnail show world map
    - Search `TBD`. Confirm result card shows a world map.

### Error conditions

TBD

### Accessibility and 508 compliance

TBD

## Code verification

- [ ] update libraries to the latest, if possible
- [ ] OWASP
- [ ] Run retire -p on client code [Retire JS](https://retirejs.github.io/retire.js/)
- [ ] Run /gradlew dependencyCheckAnalyze --info

**Comment by mcquinne** [comment]
v1.3.2 has been tagged and published
