### ISSUE TITLE
Firefox facet tag

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#322]
Weird URL encoded text in facet filter tag.

**Comment by zebdelk** [comment]
I was able to see this locally in Safari with http://localhost:8080/onestop/#/collections?(endDateTime:!n,excludeGlobal:!n,geoJSON:!n,queryText:dem,selectedFacets:(science:!('Terrestrial%20Hydrosphere%20>%20Snow/Ice')),selectedIds:!(),startDateTime:!n)

My local elasticsearch was just loaded with the DEM ETL.
