### ISSUE TITLE
Start-case instrument & platform facets

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#325]
Since we're using the long name of GCMD keywords in the 'Short Name > Long Name' format, we should standardize the appearance of the keywords in the facet menu in the same way we are doing in the collection summary view.

**Comment by ajakz** [comment]
Note: This can erroneously turn something like "TRMM Microwave Imager" into "Trmm Microwave Imager". Perhaps for both the collection summary view and facets, we only change the string to start case if `string.toUpperCase() === string`

**Comment by ajakz** [comment]
Appearance standardization of the name in the facet menu also needs to be standardized in the tags that appear when a facet is selected

**Comment by ajakz** [comment]
For confirming this works as expected (that is, all caps labels are made title-case, and care is exercised to leave acronyms alone), the test data tar file coming out of #224 has a nice collection to test against under `/EdgeCases/cleanKeywordLabels.xml`. 

The term sent to the API should remain unchanged; this only modifies the appearance of the label on the UI.

**Comment by mcquinne** [comment]
Looks good now.
