### ISSUE TITLE
Default granule link protocols when null

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#326]
Links gathered in the metadata parser are only rendered on the client if the protocol is present. Unfortunately, our metadata can frequently *not* have the protocol tag, meaning no links are rendered on the UI. We should default to something for these links, regardless.

**Comment by ajakz** [comment]
Review tip: Using testData tar file, search `ghrsst +viirs`on UI. The first result is the GHRSST collection with granules. There is a record without a protocol; the link appears as 'Web'. Protocol missing can be confirmed by looking at the JSON returned from the search request

**Comment by mcquinne** [comment]
Looks good! Thanks for the the tip on how to verify it.
