### ISSUE TITLE
Header TLC

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop#339]
Improve the header so that:

- It is built out of clear, concise components
    - e.g. `<Logo/>`, `<SearchFields/>`, `<Navigation/>`
- It lays itself out more consistently
    - e.g. consistent padding between components
- It responds to screen size changes more fluidly
    - e.g. the burger menu doesn't jump down to its own row
- The burger menu shows in I.E.

One idea is to use a `<FlexRow/>` to lay out the components and use a more programmatic  approach to watching window size and deciding when to hide, collapse, etc.

Note: Remember to debounce resize events!

Also: Keep accessibility and Internet Exploder in mine.

**Comment by zebdelk** [comment]
This has been fixed already.
