### ISSUE TITLE
routing/layout shows left filter menu on 508 (iPhone only)

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#343]
Steps to reproduce (iPhone/Safari):

- start at the landing page
- click Accessible Site link
- search for something simple like 'dem'
- the search results incorrectly show the left filter menu, which is not supposed to be part of the accessible page

Note: if we are able to retire the 508 page in the next release, we may want to mark this as Won't Fix. However, before we decide not to address this, we may want to consider making sure the layout is consistently what it is supposed to be for if/when we add additional pages / routes, even if it doesn't apply to the 508 subpage.

**Comment by ajakz** [comment]
Doesn't appear to be an issue anymore
