### ISSUE TITLE
Cache-busting for css

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#344]
Based on this release, we're not cache-busting css files.

Revisit webpack to make sure we bust the css cache as well as js.

**Comment by forgo** [comment]
need to add hash to main.bundle.js

For example, in webpack.config.js and webpack.config.prod.js:

output: {
     ...
      filename: '[name].[chunkhash].js',
    }


See:
https://webpack.js.org/guides/caching/#output_filenames
