### ISSUE TITLE
Incorporate Help docs into UI better

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#363]
Based on user feedback presented to us by MediaCurrent (and also general dissatisfaction with the existing page amongst the team...), we should make a more user-friendly help page. 

- [x] Spike on integrating github docs within our client help page
- [x] On the client help page (https://data.noaa.gov/onestop/help that links to the onestop wiki here: 
) add some intro text
- [x] Add a link to the onestop github wiki page here https://cedardevs.github.io/onestop/ on the onestop help page

**Comment by zebdelk** [comment]
I have some thoughts on more interactive help in a pseudo-popup manner (particularly for complicated sections like the filtering).

The short version is: the way the map slides out in the map filter is sort of like a popup, and we could use aria to describe it as a popup, and focus management to put the focus on the map section when it's opened and return it to the correct place in the filter when closed (this would also mean allowing the Esc key to close the 'popup'). I can picture context-specific help opening for each type of filter in a similar way.

**Comment by dneufeldcu** [comment]
Point to new github documentation pages.

**Comment by erinreeves** [comment]
Old comments:
UPDATE:
Given the decision to host docs from our repo with github pages, this issue needs to address how to direct people to that via the UI:
- Single link replacement of `Help`? 
- Help icons scattered around site that point to related section in docs?

**Comment by erinreeves** [comment]
Evan's comment:
this sounds to me like incorporating the docs build process with jekyll into our CI
like so our build process also builds the cods docs and puts them where they need to go, e.g. onto a gh-pages branch and/or into the client’s static resources (edited)

**Comment by erinreeves** [comment]
We could it seems easily use Jekyll to generate static site representing our onestop/docs module in the onestop repo.

* To indicate to Jekyll what css to use you place them in your site folder and they’ll copy across to the built site.
Tutorial/example:
https://jekyllrb.com/docs/step-by-step/07-assets/
Directory structure:
https://jekyllrb.com/docs/structure/

**Comment by erinreeves** [comment]
https://github.com/cedardevs/onestop/commit/63346e49f110885605387146b209dff35f3d032c
https://github.com/cedardevs/onestop/commit/c360096fd53a407cc241a8ebf68938ca56102241

**Comment by erinreeves** [comment]
Merged
