### ISSUE TITLE
Highlight NOAA big data links

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#378]
- [x] Matching files tab; Create a cloud icon to represent data access links referencing a URL with aws.amazon.gov (and ++ refine get info from metadata team)
- [x] Data access tab create a separate section for Access Data - use cloud icon for  cloud access e.g. look for aws, amazon, google, ibm, www.opensciencedatacloud.org

**Comment by zebdelk** [comment]
We added protocol = "cloud" and function = fileAccess to support the PSI demo.
