### ISSUE TITLE
MediaCurrent - WCAG items

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#387]
Review and update WGAC requests from MediaCurrent that didn't ship with 1.3.x

- [x ] Skip navigation links in header - replaced with
  - [ ] ensure cursor focus after moving to search results page is at top of filters (auto skips past header) (and also moving to details page)
  - [ ] landing page - default cursor focus to search box (research how best to mitigate this for blind users)
- [x] Review and fix reported wave errors (currently 7 in 2.0 beta)
- [x] Replace background image for improved color conrast

**Comment by dneufeldcu** [comment]
Here's some documentation. https://webaim.org/techniques/skipnav/

**Comment by mcquinne** [comment]
Another resource: http://www.jimthatcher.com/skipnav.htm

**Comment by zebdelk** [comment]
Another resource: https://www.w3.org/WAI/WCAG20/quickref/?currentsidebar=%23col_overview#navigation-mechanisms-skip
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html
(Note "Each numbered item in this section represents a technique or combination of techniques that the WCAG Working Group deems sufficient for meeting this Success Criterion. However, it is not necessary to use these particular techniques.")

**Comment by zebdelk** [comment]
- [ ] ensure cursor focus after moving to search results page is at top of filters (auto skips past header) (and also moving to details page)
- [ ] landing page - default cursor focus to search box (research how best to mitigate this for blind users)

**Comment by zebdelk** [comment]
Focus changes covered by #550
