### ISSUE TITLE
Ensure one mapping per index

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#390]
As of ES 6.x, types in indices are deprecated. Even though we're only migrating to ES 5, we should plan for this and only have one type (not named -- use index name to clarify, e.g., search-granule) per index.

**Comment by mcquinne** [comment]
Alternate idea: Use the same mapping in a single index for both types, but include our own "type" field for filtering.

**Comment by zebdelk** [comment]
Completed and reviewed as part of #494
