### ISSUE TITLE
Migration to ES 5.6 or later requires script change

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#393]
The 'inline' field in ES scripts is deprecated from 5.6 onward and needs to be changed to 'source'. We only need to do this once production is upgraded past ES 5.5

**Comment by dneufeldcu** [comment]
Does this mean we'll be ES 6 compatible once this story is complete?

**Comment by ajakz** [comment]
@dneufeldcu Almost. We have one last thing to change, which is totally different between ES 5.x and ES 6.x: the default type name. That's a one line code change to be functional on both 5.6.x and 6.x, but it'd be nice to take advantage of some 6.x-only features eventually, too, like pipeline changes.
