### ISSUE TITLE
Exclude "No spatial bounding" and "No time period" in results

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#402]
we have an "exclude global" spatial filter option which prevents results which span the entire earth, but we don't have a way to filter out items that have no spatial bounding whatsoever -- same thing for no time range specified.

We should think about adding these features to the API to improve searchability.

**Comment by ajakz** [comment]
May want to think of this being done with a radio button -- show all, show only results with spatial(/temporal) bounding, show only results without spatial(/temporal) bounding.

**Comment by mcquinne** [comment]
Note: This might be better suited for search optimization epic if it doesn't require changes at ingest time.
