### ISSUE TITLE
Leaflet <--> manual coordinate entry should stay within [-180, 180] and [-90, 90]

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#405]
Because Leaflet lets you move the map all over the place, drawing across the dateline results in coordinates outside of the desired range. This makes the manual entry boxes not get populated, the selected area doesn't show up on the map when it's re-rendered, and the filter tag doesn't show up... all despite a proper filter being applied.

Note -- this inability to re-render the created geometry on the map is a long-existing bug.

This can likely be resolved by taking advantage of the ensureDatelineFriendlyPolygon method in geoUtils

**Comment by dneufeldcu** [comment]
maxBounds could also be set as an alternative

**Comment by zebdelk** [comment]
Another confusing map inconsistency to fix:

- [ ] typing in coordinates with North < South should result in a validation error (currently N: 42, S: 40 results in the exact same bounding box as N:40, S:42)
- [ ] typing in coordinates with West > East should invert the bounding box vs East > West. For example:
  - W: 80, S: -90, E: -80, N: 90 should be the opposite selection from W: -80, S: -90, E: 80, N: 90, but is currently the exact same bounding box.

**Comment by forgo** [comment]
- Upgrade to ‘leaflet’, ‘leaflet-draw’, and ‘esri-leaflet’
- “Limit map size” — centered and max-width
- use Leaflet maxBoundsViscosity to prevent excessive scrolling

Still to be addressed:
- Updates caused the “ImageryLabel” baseman not to show. Though the “Imagery” baseman is being added in the same way, and shows up fine. Might this be an API change?
- Even though we’ve prevented the map from stretching excessively in the East/West directions, there are still ways to cross the dateline which prevent the bounding box from being drawn (doesn’t appear to affect the actual search).

**Comment by ajakz** [comment]
This has been resolved in the 405-leafletOutOfBounds branch
