### ISSUE TITLE
Limit map size

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#407]
On a very large screen resolution, given that the map extends the entire width of the results area, the map repeats several times. We should limit the map to being 1 earth-width, since this repetition is awkward. 
This is likely a good place to limit how much the map can be "spun" as well, which will alleviate some of the issues with rendering geometries.

**Comment by forgo** [comment]
this was already addressed and pushed to the 405 branch... as it is two CSS properties, I opted to not create a separate branch. the fix can be seen on 405

**Comment by zebdelk** [comment]
Review: I reviewed the code and behavior changes, and it looks good. Close this ticket when we merge the branch to master.

**Comment by zebdelk** [comment]
Fixed on #405 branch.
