### ISSUE TITLE
Collection results list: more heading levels than needed.

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#418]
For the current collection view, having H2 for all the titles of results, when no other information is included in the results list, is actually harder to navigate (since cycling through all the headers than takes even longer to get a sense of page contents).

If the view continues to be only a list of titles, it would be more helpful to just have a list of links/buttons.

If the view changes, so that each result has multiple pieces of information (ie title, description, etc), then the headings are useful and should be part of that layout.

**Comment by dneufeldcu** [comment]
Achieved AA standards
