### ISSUE TITLE
Tree view improvement

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#422]
Suggested by AUL: Change the tree view to read the checkbox first, then the rest of the label and status.

This makes it easier to identify that there is a facet to toggle on or off.

Note that because fully blind users cannot skim, they sometimes skip before a long description finishes reading. Moving the checkbox forward in reading order helps communicate the most critical information first.

**Comment by dneufeldcu** [comment]
Achieved AA standards
