### ISSUE TITLE
Facet Capitalization Consistency (logic migrated to API)

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#435]
- [ ] Remove superfluous logic from keyword utils (api should provide clean capitalization for all keywords)
- [ ] Revisit difference in display between keywords in filter menu vs keywords in applied filter bubbles (one splits on '>', while one does not), specifically in categories besides data theme

Depends on #309

**Comment by ajakz** [comment]
Addressed as part of #309
