### ISSUE TITLE
Search map recentering bug

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#438]
This issue presents itself when using the map to draw a geometry by which to search. The first search returned from this will apply the filter but any subsequent filters applied will drop the geometry as it is not stored in redux if it is not parsed to [-180, 180] (this is by intention!).

The code that specifically needs to be fixed is recenterGeometry() in geoUtils.js. If something is recentered to [-360, 0] or [0, 360], the rotations cease as expected. However, if the geometry crosses neither the prime meridian or date line, the East or West coordinate needs to be shifted again by |360| degrees.

There are two ways in which it can be demonstrated:
- Pan the map to *right* a few revolutions and draw a box around Florida. The map will recenter itself to the coordinates in the query string (something like g= *270.1758*, 17.113, -69.4336, 36.1426) but the box will neither be drawn nor will the text boxes be populated. The map SHOULD recenter one more turn to the left to roughly g= *-90.1758*, 16.436, -69.7852, 36.7047.
- The same bug presents itself when rotating this time to the *left* and drawing over Australia.  (Recenters to roughly g= 108.1055, -43.2169, *-199.5117*, -3.0328 instead of roughly g= 109.1602, -43.4735, *158.3789*, -6.5356). 
- Selecting the above regions when rotating the map in the OPPOSITE direction will recenter correctly

**Comment by zebdelk** [comment]
This is fixed on the #405 branch.
