### ISSUE TITLE
Collection detail: back to search breadcrumb

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#443]
- [ ] use the redux state to return the view to the original search (link at top of collection view)
- [ ] if the URL is loaded directly, with no search params or redux store, do not include this link

**Comment by zebdelk** [comment]
See also ld+json for breadcrumbs: https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by dneufeldcu** [comment]
Not a priority.
