### ISSUE TITLE
Ingest spatial bounding as string

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#458]
Spun off from talking with metadata folks, we don't want to add any new ways of generating geoJSON from metadata but we do want to ingest xml elements as string/nested object into staging for potential future use

**Comment by dneufeldcu** [comment]
Discussed and decided to pull this out of mappings scope  relabeling as future feature; More discussion with metadata team needed - explore use of convex hull operation for line features to generate the minimum bounding polygon (which is supported in ISO).  This would ideally happen upstream of OneStop.
