### ISSUE TITLE
Review API tests for appropriate edge cases

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#460]
Brainstorm cases we should be testing in our API, and make sure we are doing so. Examples of things to consider:
- [ ] Empty fields (null) **and** empty arrays ([]) are being investigated in granule flattening
- [ ] Fields that shouldn't be ingested aren't
- [ ] Repetition (or lack thereof) in the XML of any nodes doesn't cause issues
- [ ] Filtering on ingest works as expected
- [ ] Filtering on Staging -> Search works as expected

**Comment by zebdelk** [comment]
These are either PSI and complete, or will be redone when we tie the systems together!
