### ISSUE TITLE
Add line check to spatialBounding creation

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#461]
Like we presently do for points, we should see if a given "polygon" in the metadata is actually a line and create the corresponding geoJSON for ingest into ES. Right now, "polygons" that are actually lines are rejected and the metadata isn't ingested.

**Comment by zebdelk** [comment]
Follow up with more conversations on this practice.

**Comment by dneufeldcu** [comment]
Removing bug label; Lines are not supported in the ISO standard. Added future-feature label

**Comment by ajakz** [comment]
Use attached file (copy to XML before loading -- couldn't upload XML to github) to test. This line crosses the dateline as well to show that works too. Search for "glacier"; record title is "LINE GEOMETRY TEST". If using the testData tarball, this search will also turn up the point record (same image on collection) in addition to a third record that has a bounding box.

[lineXML.txt](https://github.com/cedardevs/onestop/files/1820884/lineXML.txt)
