### ISSUE TITLE
Add ingest pipeline & search mapping endpoints to admin controller

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#492]
Add ability to update the ingest pipelines and search mappings via the admin controller of the metadata api. This will allow us to make changes without requiring an unnecessary redeploy and/or reindex. 
- [ ] Use '[RELEASE-DATE]' (or version field?) in pipeline description to check, on startup, if pipeline definition compiled with code is newer than (if exists) ES-stored definition
- [ ] Create endpoint to reset pipeline to one compiled with code?

**Comment by dneufeldcu** [comment]
Intention:

Be able to modify what is in the search index more dynamically without bringing down the API.

Pipelines may not be the best mechanism for this in the future, and the pipelines for staging may go away anyway.
