### ISSUE TITLE
Review and update wiki documentation

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#516]
Decide what should be maintained and update as needed

- [x] Our release process has changed review edits from PO and remove older unused steps.

https://github.com/cedardevs/onestop/wiki/Internal-Development-Practices

**Comment by ajakz** [comment]
Tasks:
- [x] Update & clarify options on Search Request page
- [x] Add Search Response page
- [ ] Update API Deployment Overview
- [x] Update Client Deployment Overview
- [x] Update App Config
- [ ] Update Metadata Indexing Details
