### ISSUE TITLE
Change isRelease to be CLI args

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#519]
In publishing.gradle , we have

// if not a release, publish snapshot versions
if (!isRelease) {
  version = version += '-SNAPSHOT'
}

We need to create non-snapshot artifacts for partner when building locally. So allow an isRelease flag to be passed to gradle in the build?

**Comment by zebdelk** [comment]
I've made some tweaks to the build.

Starting with 2.0.0-RC3, `gradle build` will not automatically append -SNAPSHOT to the version. This change should apply to local builds, but not to Travis builds. Builds automated by Travis are still expected to append -SNAPSHOT unless they are tagged, the same as our existing release process.
