### ISSUE TITLE
Add metadata test data for CU server updates

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#530]
Metadata test data and load updates (CU server)
- [x]  Add or identify a metadata record with line in bbox (Example: https://drive.google.com/open?id=0BxaVtlmPt2jIbFJxY0I1a2hlWFZmRms3VnNDWGJpQ1kzUUM0)
- [x]  Add or identify a metadata record with citation info
- [x] As another edge case, we should have a collection with a DOI and granules referencing the collection's fileIdentifier and DOI in the parentIdentifier field to confirm both work as expected (both granules are associated with the collection). Release checklist should be updated to confirm this as well.

**Comment by forgo** [comment]
add to test data jar and release checklist
