### ISSUE TITLE
ORR

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#545]

**Comment by forgo** [comment]
[x] IE featured dataset width ratio
[x] IE remove default browser clear input button
[x] IE fix alignment of clear button on small screen width
[x] remove weird firefox dotted lines
[x] Help/About font/style update
[x] clean up search field styles and heights (consistent across browsers/fonts)
[x] tabs flex 100% width again
[x] horizontal center the image for featured datasets when image is very small

**Comment by zebdelk** [comment]
I've reviewed these changes, and we got them into the latest release candidate.
