### ISSUE TITLE
Fix OWASP jackson data bind CVE

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#554]
Need to upgrade to 2.9.5

See potential solution from PSI - this is how we avoided the vulnerable jackson-databind dependency in psi: https://github.com/cedardevs/psi/blob/master/build.gradle

https://nvd.nist.gov/view/vuln/search-results?adv_search=true&cves=on&cpe_version=cpe%3A%2Fa%3Afasterxml%3Ajackson-databind%3A2.9.3

**Comment by zebdelk** [comment]
Fixed for 2.0.0-RC6
