### ISSUE TITLE
Collection Access - content and order

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#556]
Feedback on the access tab:

Metadata Team Request:
- add a section for linkFunction == search
- add a section for linkFunction "Online Access" (TODO - double check if the exact function match is onlineAccess or something else)

Suggestion:
- show Download Data before Information

**Comment by zebdelk** [comment]
Tentative conclusion: download, search, order, offlineAccess, fileAccess, "Other Access" (no function code, or not matching one of the previously specified options).

Full function code list: https://geo-ide.noaa.gov/wiki/index.php?title=ISO_19115_and_19115-2_CodeList_Dictionaries#CI_OnLineFunctionCode

"Other Access" example: https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.ngdc.mgg.geophysics:G01402

**Comment by dneufeldcu** [comment]
obe
