### ISSUE TITLE
508: Various issues from release checklist

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#559]
- IE: submit search from landing page - focus is set by browser to top after our focus code runs
- IE: details page is treating that top header in focus as a interactive widget and changing the screen reader mode
- IE: video tab has accessibility issues (particularly, playing the video steals focus and doesn't seem to give it back)
- contrast issues 
  - it looks like white text on our lighter-blue theme color (space and time filters) is still an issue, but our new styling has resolved the other ones.
  - details page, white on the medium blue
  - link colors
  - granules list - some of the badge colors

**Comment by dneufeldcu** [comment]
obe
