### ISSUE TITLE
Migrate OneStop CI + automate owasp/retirejs

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#579]
From travis to circle

- [x] Allow OWASP to be part of automated build
- [x] Run retirejs as part of automated build (using `npm run retire`)
- [x] both of these tasks should run with `gradle check`

**Comment by StrayCat1** [comment]
retire already ran before check for the client. Made check depend on OWSAP dependency check

**Comment by zebdelk** [comment]
I removed the requirement that all builds run the owasp check and switched to a daily cron on circle.

The justification of this is a CVE on the H2 dependency. There is no newer version to upgrade to, and after discussing it, we concluded that it was unwise to issue a suppression. The longer-term plan is to replace H2 with a real database, or remove it when we tag a release. Either way, we don't want situations like this to cause all our builds to break.
