### ISSUE TITLE
Host API Docs / deploy swagger-ui?

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#585]
- use swagger-codegen to generate static html docs once the 3.0 release is available?
- deploy swagger-ui as part of our docker stack?
- link wiki to openAPI file in github (sadly can't bookmark live swagger ui demo)
- do we need an endpoint to get the openAPI descriptor file from?

**Comment by zebdelk** [comment]
run against a local dev directory: `docker run -p 80:8080 -e SWAGGER_JSON=/foo/openapi.yml -v ${ONESTOP_PROJECT_DIR}/api-search/src/main/resources:/foo:ro swaggerapi/swagger-ui:v3.13.3` works well to display the API - deploy that image in the stack with the correct api file, and make it available with nginx config.

**Comment by zebdelk** [comment]
https://github.com/swagger-api/swagger-codegen/releases

3.0.0-rc0 is the latest release candidate, which should work with OpenAPI 3.0.0 once it's available. Once available, it should have a docker version, and possibly the gradle integration to use directly.

Specifically, I'd expect to use it to:
- [ ] generate static html api documentation
- [ ] convert the yaml to json as part of the build (I've lost track of the page that suggested this was the correct project for that functionality, but as far as I know, it is)

**Comment by zebdelk** [comment]
also potentially of interest: https://github.com/swagger-api/validator-badge

**Comment by mcquinne** [comment]
Instead of hosting these ourselves, we shall use swaggerhub! https://app.swaggerhub.com/apis/cedardevs/one-stop_search_api/2.0.0
