### ISSUE TITLE
Swagger doc for response values in API

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#586]
- [x] expand description of collection and granule responses to be more useful
  - should include which fields are always returned (summary fields)
  - import from ES mapping, to minimize chances of getting out of sync and manual effort, if possible

**Comment by StrayCat1** [comment]
Search responses are documented in the OpenAPI spec here - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/search/schema/openapi.yml#L648 which references the part of the response with all the properties - https://github.com/cedardevs/onestop/blob/1020-OneStopCLI/search/schema/openapi.yml#L598

Are we looking to document the response when summary=false?

**Comment by StrayCat1** [comment]
allOf not working in the full response. 
https://github.com/swagger-api/swagger-editor/issues/476
