### ISSUE TITLE
JSON LD support in collection detail view

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#593]
JSON LD support improves search engine optimization both for major search engines.  NODC has implemented it within there collection pages wrapped in a script tag.  

See / view source: https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.nodc:SAR-WINDS-S1

Tasks:
- [ ] JSON-LD is embedded in the collection detail page

**Comment by zebdelk** [comment]
Related to #514
