### ISSUE TITLE
SAML or OpenId authentication works

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#612]

**Comment by forgo** [comment]
This story is just to confirm that we can succesfully do SP or IdP-initiated authentication via SAML (ICAM or login.gov). login.gov provides OpenId, but for consistency with ICAM, we are using SAML for now.

**Comment by rongxanh88** [comment]
Reviewed and confirmed functionality of SAML authentication with login.gov after merging branch into my authorization code.
