### ISSUE TITLE
Write script that lists public search strings

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#614]

**Comment by CoopTang** [comment]
Search queries and filters with their respective occurrences have been output to individual .csv files and uploaded to the shared SearchRelavency folder in Google Drive.

**Comment by rongxanh88** [comment]
[Name of Thing](http://localhost:8080)

**Comment by rongxanh88** [comment]
Reviewed: [Comments in Pull Request](https://github.com/cedardevs/Search-Relevancy/pull/1)
