### ISSUE TITLE
Web team feed back (round 2)

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#617]
See latest write-up and task out in this story.  Note items that may need to be deferred or discussed. https://drive.google.com/drive/u/0/folders/1e0IRdYVT4yhzVG1uhL5cCrheL-ywAPYO

**Comment by zebdelk** [comment]
- [ ] Creative Commons footer link
- [ ] OneStop Logo link title
- [ ] bad H2 on about and help pages
- [ ] map draw / bounding box instruction clarity
- [ ] focus style on results "show more" button
- [ ] double check alt text for search result thumbnails
- [ ] double check for updates/issues/configuration options with leaflet
- [ ] focus style on files/citation/identifier sections of collection detail page
- [ ] dsmm contrast
- [ ] email follow up for clarity on map bounding box label issue
- [ ] document several things outside agile control for web team
- [ ] decide medium complexity issues
