### ISSUE TITLE
Cloud protocol updates

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#619]
Ensure we are supporting cloud protocols:

Google:GCP:GCS
Google:GCP:BigQuery
Amazon:AWS:S3
https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv
- [x] Feature implemented

**Comment by zebdelk** [comment]
This should be included in 2.0.0 RC9, but it would be nice to make some test data to verify it's working as expected.

**Comment by dneufeldcu** [comment]
Test data is to be provided by metadata team
