### ISSUE TITLE
Trending searches: write logstash grok pattern to parse OS Logs

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#637]
As a developer, I have onestop logs passed through a grok filter.

http://grokdebug.herokuapp.com/
Input: 1 line from the log file
Pattern: [this is the part that we need to write]
Hopefully we won’t need custom patterns
Expected Output: We may need to iterate on this, but I’m currently expecting something like ```{
"timestamp": ...,
"method": "POST",
"entity": "collection",
"action": "search",
"queryterm": "oceans",
"geometryfilter": ...,
"timefilter": ...
}```

See also:

https://github.com/elastic/logstash/blob/v1.4.2/patterns/grok-patterns

https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html

**Comment by CoopTang** [comment]
See PR #689
