### ISSUE TITLE
Select granules for download

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#638]
Given that a user is on the granule/file list page, then, if a file has a link with the Download protocol:
- [x] There is a key in the redux store with selected granules
- [x] There is a button on each granule card to select/deselect the granule
- [ ] There is a button at the top of the search results to select-all
- [x] Selected granules have an easy-to-understand and accessible way to indicate that they are in the cart

**Comment by forgo** [comment]
Merging into #683

**Comment by zebdelk** [comment]
We have a new plan for how to add granules to the cart, which makes the need to complete this type of select-all unnecessary
