### ISSUE TITLE
Document Agreements with Common Access

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#643]
Review and discuss JSON API requirement for CA with with CA team. Make sure to include PSI in any discussions.

Given an agreement of the package API specification endpoint with Common Access

- [ ] I have a document with agreed upon JSON request
- [ ] I have a Swagger doc describing this API
- [ ] I have a document with deployment status information (so we know if the API is available in test, dev, or prod and toggle our own features appropriately)

**Comment by dneufeldcu** [comment]
OBE - Common Access will be used to support legacy datasets; Metadata team responsible for creating metdata so that access page goes to appropriate Common Access page.
