### ISSUE TITLE
Wireframe select granules

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#651]

**Comment by forgo** [comment]
Prototype/mock a UI for how granules will be selected for an order via CA.

**Comment by zebdelk** [comment]
![granule search page.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46ef869b2d978faccffaba42b65ef8d4394720766b48e13b628ae92dbc56395b4d5a47ad120b0d15fbfe8b23a4e53570885e58e9d36b0d77c52f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e48a884a391a04108df65b27ed.png)

**Comment by zebdelk** [comment]
https://drive.google.com/open?id=1wz5HlI5IbWyQJMZWF5GfvWEvWzCfA81A
