### ISSUE TITLE
Wireframe shopping cart

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#652]

**Comment by forgo** [comment]
Prototype/mock a UI for how selected granules will be ordered and confirmed from CA.

**Comment by zebdelk** [comment]
![file cart.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46ee9d9626c280a89dfdfd0fe64de29b234324676b5ee17e29d4e02bbd432c565d574cff48585d46affd8b2df4b53f62964e49bc8f3900299f7744eeaa880dbe08b0218e4c84b1b98d4fc9e0342ce599c2.png)

**Comment by zebdelk** [comment]
https://drive.google.com/open?id=1Nuk3Arm2lHC-99ptBHuY8s5mk08JEuHB
