### ISSUE TITLE
User saved search api

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#673]
Given an id for a logged-in user and valid search parameters, when a POST is made to /onestop/api/bookmark/collectionSearch:

- [ ] a new row is created in the postgres table for bookmarked collection searches
- [ ] if a user already has the maximum number of bookmarks allowed, an error is returned

Given an id for a logged-in user and valid existing bookmarked search id, when a DELETE is made to /onestop/api/bookmark/collectionSearch/[bookmarkId]:

- [ ] the row in the table is removed
  - requiring the user id that created the bookmark prevents random bookmarks being deleted by id from users who do not have the authority to do so (this works best if the user id is a uuid from the login service and not their email)

Given an id for a logged-in user, a valid bookmark id, and update request, when a PUT is made to /onestop/api/bookmark/collectionSearch/[bookmarkId]:

- [ ] the request is updated
  - intended to be used to update the number of results the last time the search was run
  - may also be used to allow users to update the name of their search

**Comment by dneufeldcu** [comment]
Duplicate #1184
