### ISSUE TITLE
Clarify AOP Requirements for end of quarter goals

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#677]
CA API only supports specific dataset use cases along with search capabilities (for those datasets) which do not overlap perfectly with OneStop searches.

It is not currently on the CA roadmap to implement something more compatible with OS needs prior to Inventory Manager integration.

Given that, we need to clarify what an acceptable level of actionable integration is to meet the AOP.

[ ] updated AOP goals

Note that #641 will include spikes of options we can build and demo as well.

**Comment by dneufeldcu** [comment]
No need to track progress on AOP via story.
