### ISSUE TITLE
Spike - api-metadata loading by token

### ISSUE THREAD

**Issue by rongxanh88** [cedardevs/onestop#679]
TIMEBOX: 1/2 day to 1 day (if there is promise)

Scope: What are we doing for 2.1

Context:
There is currently no way to integration test api-metadata in Kubernetes.

User Story: As a developer, I want to type a command in terminal, and test uploading metadata to the kubernetes cluster.

Acceptance Criteria:
- [ ] Choose a design pattern to implement this feature.
- [ ] A simple one line command in terminal tests uploading metadata and verifies result.

**Comment by dneufeldcu** [comment]
OBE CAS meets this need on-prem for secured script based loading.
