### ISSUE TITLE
Granule search view list/card toggle (MediaCurrent suggestion)

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#682]
- [ ] search result page: add list view toggle
![Screen Shot 2018-01-09 at 10.47.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591b3ded1d376e001ad78dc3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2f56415e4dbc30254d58eeb9cb74fce36f34985619e8d86c0c27946c16abba8a1dec08ba22891c81b4bad84fc3fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae44857a4133061e677336e0a.png)

**Comment by ajakz** [comment]
This has been completed
