### ISSUE TITLE
SP Metadata in repo

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#704]
Check our SP metadata files into a secure repo and manage as part of our release process (CU-admin-server or help or ?)

This will in the future with a more repeatable process.

**Comment by forgo** [comment]
metadata now in private 'help' repo:
https://github.com/cedardevs/help/tree/master/saml/sp-metadata/icam

and linked properly within 'help' wiki:
https://github.com/cedardevs/help/wiki/SAML-Authentication-and-Authorization#idp-doc
