### ISSUE TITLE
EPIC: ElasticSearch Upgrade 6+

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#730]
**Summary**
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer of OneStop</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>implement a migration strategy from ES 5.x -> 6.x</td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>support the federal ES 6.x cluster (currently at 6.6) and future upgrades</td>
  </tr>
</table>

**Sprint**
April 15 - April 26

**Assumptions**
- ES6 is now the default, if we need a bug fix on ES5 use local dev + federal test tier
- we do not want to support multiple versions in our dev environment
- future production upgrades may necessitate code changes, but:
  - we can mitigate risk by dynamically determining ES version
  - log and prevent API from starting if ES version is not supported

**Tasks**
- [x] #866 
- [x] #868 
- [x] #869 
- [x] ETL #929

**References**
<table>
  <tr>
    <td><b>Point of contact</b></td>
    <td>who manages federal ES upgrades?</td>
  </tr>
  <tr>
    <td><b>Doc, Spreadsheet, etc.</b></td>
    <td>none</td>
  </tr>
</table>

**Comment by dneufeldcu** [comment]
Revisit, think about utilizing new features like:
Auto suggester - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
Trending searches - https://www.elastic.co/guide/en/elasticsearch/reference/6.x/search-aggregations-metrics-top-hits-aggregation.html
