### ISSUE TITLE
Error not reported when ES connection fails

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#739]
Search-api doesn't respond correctly with an error when the app is unable to connect to ElasticSearch. The client shows a white page as opposed to the error page.

**Comment by mcquinne** [comment]
Let's revive this story!

- [ ] check if is still a problem
- [ ] fix it if it is!

**Comment by erinreeves** [comment]
Not reproducible. Now displays the red banner message "Something went wrong"... ES responds with a 500 ATM, but this story seems to be about how the UI handles the error.
