### ISSUE TITLE
Update sitemaps & test indexing

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#757]
Sitemaps need to be updated to reflect the URL changes from moving to browser history.

We also need to decide on our testing strategy, since we don't want demo data to show up as though it were real results, ideally.

- [x] update sitemap urls
- [x] redirect from old collection urls to new ones (presumes IDs have not changed, but will make future deployments less headache inducing if so)
- [ ] update sciapps deployment
  - blocked by #788
- [x] determine small subset of data to use for SEO testing / focus on demo

**Comment by dneufeldcu** [comment]
Not sure how this is blocked by #788 since we verified JSON-LD on sciapps yesterday.
