### ISSUE TITLE
ElasticSearch upgrade to 5.x latest

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#761]
Partner environment now at 5.6.31

- [x] client libraries updated
- [x]  local dev and sciapss env updated

**Comment by mcquinne** [comment]
FYI - The client library is now named `elasticsearch-rest-client` (as opposed to just `rest`). This is the "low level rest client" (which is what we were already using) as opposed to `elasticsearch-rest-high-level-client` which was introduced with 5.6 and contains over-engineered java builders like the older client that we moved away from some time ago. For more info see: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-overview.html
