### ISSUE TITLE
Orphaned Form Label

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#795]
"Orphaned form label" for filter instructions (applies to Location, Date and Keyword instructions)

You can see this with WAVE, as a yellow alert when it's triggered with one of the filters open.

- [ ] Use `<fieldset>` and `<legend>` instead of `<label>` for filter instructions

From MediaCurrent's A & AA findings.

**Comment by StrayCat1** [comment]
@zebdelk Can I get some more clarification on this story? I see the `<label>` blocks in the MapFilter, for example, but I am not sure what changing them to `<legend>` or `<fileset>` is exactly supposed to accomplish.

**Comment by StrayCat1** [comment]
Wave and ANDI to test the difference
