### ISSUE TITLE
Hover Contrast

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#797]
The main navigation links in the header (Home, About, Help, etc) do not meet contrast requirements with the hover color.

Minimum requirement: 3:1 ratio between the hover text color and the background color (to meet AA level)

Optimal: 4.5:1 ratio (meets AAA level)

From MediaCurrent's A & AA findings.

- [x] the navigation links hover color should meet 3:1 or 4.5:1 (preferred) contrast against the header background color

**Comment by StrayCat1** [comment]
Used color from topic icons for a contrast ratio of 5.38:1 

Used https://webaim.org/resources/contrastchecker/ to check

**Comment by StrayCat1** [comment]
https://github.com/cedardevs/onestop/pull/901
