### ISSUE TITLE
Location Filter Focus

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#798]
Focus does not move as expected.

After using the Show Map button, focus does not move to map, and it is not next in focus order.

Suggested solution: treat map as though it is a popup.
- [ ] use the correct roles and markup to indicate it is a popup
- [ ] focus automatically jumps to beginning of map controls
- [ ] closing map returns focus to Show Map button
- [ ] esc button
- [ ] tab order while "popup" is open should stay within the popup instead of through the entire page

From MediaCurrent's A & AA findings.

**Comment by dneufeldcu** [comment]
Elliott / Zeb discussed on 8/8 and the effort is time boxed at 2 days.

**Comment by zebdelk** [comment]
Instead of doing a popup, since that had user experience implications the team decided we didn't care for in this case, we chose to go down the path of putting the map inline with the filter (as far as dom and tab order are concerned) and using css to position it where we want it.

Everything is working except we need to revisit the animations and make sure they're handled smoothly.

WIP is on branch `map-tab-order (20 minutes ago)`
