### ISSUE TITLE
Search Results Pages - context and order

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#800]
- [x] Page title should provide context (query text that was searched for)
- [x] Add an H1 which matches the page title minus "on NOAA OneStop", provides context (query text that was searched for)
  - [ ]  H1 appears before the filter section in the DOM
- [x] Filter section heading should be an H2 and headings underneath it should be adjusted accordingly
- [ ] Existing list view heading should be an H@ and headings underneath it should be adjusted accordingly
- [ ] Apply this same header logic to other view, e.g. cart, granule results, etc.

H1 and page title should indicate search terms (i.e. the queryText from the redux store) to assist users with linear navigation experience such as screen readers to maintain context.

Logical order of the page (DOM structure) should put the H1 before the filters instead of after.

From MediaCurrent's A & AA findings.

**Comment by StrayCat1** [comment]
For clarity :
 The first two checkboxes are referring to the H1 in the ListView, specifically when it is used by the CollectionList and GranuleList components. Found here- 
https://github.com/cedardevs/onestop/blob/master/client/src/components/common/ui/ListView.jsx#L141

Currently those result pages say something like "Search Results (showing 8 of 8)", but we want to want to be more specific. For example, "Showing 8 of 8 matching collections".

**Comment by StrayCat1** [comment]
On closer inspection, maybe all we are talking about is updating this is the "Collections" component. 
https://github.com/cedardevs/onestop/blob/master/client/src/components/results/collections/Collections.jsx#L48

These usages seem to be more specific 
https://github.com/cedardevs/onestop/search?q=resultsMessage&unscoped_q=resultsMessage
