### ISSUE TITLE
/sitemap.xml incorrectly requests login

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#822]

**Comment by forgo** [comment]
This may have been addressed in:
https://github.com/cedardevs/onestop/pull/816

But we should double check. It appears like our previous security filter looked for `/sitemap/**`. There may still be endpoints there to bypass security, but the `/sitemap.xml` at the root doesn't pass the security filter.

**Comment by dneufeldcu** [comment]
Still an in issue on 2/15/2019, https://sciapps.colorado.edu/onestop/api/sitemap.xml still redirecting to login.gov
