### ISSUE TITLE
File access / download 2nd pass

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#823]
- [x] Simplify right-hand menu in header
-- About | Help where about is a drop-down with menu options
-- Cart icon prominent doesn't require clicking burger menu
--  Eliminate burger?
- [x] Revise icon + 'Download wget script' to icon + 'Links'
-- Change color of button to blue (from  green)
-- Vertically align with Clear button
- [x] Smaller font for granule titles
- [x] Add context sensitive help
![IMG_1620.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591ccb952fa3730020d900a6/125516c66e82c728ace21e0d46c1b9bd1cd3d5fbdfabf301b44fff9e2c4533317346f6722186e02abe152c53575d1da5415a5d17f8fb8f79a5b52e6c981e5ab38532022d8c6853beb2901eb90bbb258f478cb1b98e4cc9ec3a2df5c6.JPG)

**Comment by zebdelk** [comment]
closed by PR #830
