### ISSUE TITLE
change relative api path to onestop-search

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#827]
motivation: this will make deployment and configuration easier for both us and ops.

- [x] deploy api-search relative path to /onestop-search instead of /onestop/api
- [x] update client code to look for api at /onestop-search/
- [x] change api-search war name to onestop-search.war
- [x] deploy api-metadata context path as /onestop-admin/
- [x] change api-metadata war name to onestop-metadata.war
- [ ] update icam
- [ ] update login.gov

**Comment by dneufeldcu** [comment]
ICAM feature toggle off
