### ISSUE TITLE
SpatialBounding incorrectly recorded as null by loader

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#846]
Spatial extents with a value of 0 in a single coordinate are being recorded as spatialBounding null.

- [x] OneStop loading code
- [x] PSI loading code

The following collection record is an example:

https://data.noaa.gov/onestop/#/collections/details/AWbw41dXYJ6J3EnSGyHm?q=%2BNDBC%20%2BC-MAN

https://data.noaa.gov/onestop/api/collection/AWbw41dXYJ6J3EnSGyHm

Eg.:

-<gmd:westBoundLongitude>

<gco:Decimal>-177.8</gco:Decimal>

</gmd:westBoundLongitude>

-<gmd:eastBoundLongitude>

<gco:Decimal>-66.6</gco:Decimal>

</gmd:eastBoundLongitude>

-<gmd:southBoundLatitude>

<gco:Decimal>0</gco:Decimal>

</gmd:southBoundLatitude>

-<gmd:northBoundLatitude>

<gco:Decimal>61.1</gco:Decimal>

</gmd:northBoundLatitude>

[Uploading cman_spatialBounds.xml.txt...]

**Comment by zebdelk** [comment]
closed by PR 854 in onestop, and PR 301 in psi
