### ISSUE TITLE
Make About and Help views screen reader accessible

### ISSUE THREAD

**Issue by ajakz** [cedardevs/onestop#85]
Revisit look and feel
- [x] Help standalone page
- [x] About standalone page
- [x] Move collection & granule count to about page
- [x] Confirm 508 compliant

When a screen reader user clicks the About and Help links, the focus is not shifted to the modals and no notification of any changes is given. 

The focus should jump to the opened panels when the links are clicked. There should also be a clearly identified button to close the panel, after which the focus returns to the button clicked in the navigation menu.

**Comment by mcquinne** [comment]
Also: Maybe we move the collection/granule count(s) into the about section so it's not the front page.

**Comment by dneufeldcu** [comment]
Make Help and About there own pages.  Add more content to About.
