### ISSUE TITLE
time logic relationship errors

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#850]
Background:
Review from paleo group revealed a bug in the relationships for time filters. Contains/Within/Intersects/Disjoint worked in most cases, but are sometimes inconsistent with expected results.

Tasks:
  - [x] Review logic
  - [x] Fix elasticsearch queries
  - [x] Update tests

Story Owner:
@ajakz

**Comment by zebdelk** [comment]
Moving most of this content to #857, since this ticket was used to resolve a bug revealed by the paleo documentation and review
