### ISSUE TITLE
Metadata loading error

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#851]
Help the metadata content team debug a load error being thrown.

Wed Mar 13 13:14:05 EDT 2019 - 
Uploading ferret.pmel.noaa.gov/uafwaf/iso/granule/keo_121f_a3d0_3c0a.xml: 
{"errors":[{"status":400,"title":"Load request failed due to malformed data.","detail":"WrappedRuntimeException: 
Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)"}]}

[keo_121f_a3d0_3c0a.xml.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/591ccb952fa3730020d900a6/125516c66e82c728ace21e0d46e391951cd3d1f889d6be10a00dcfc72a16263d3109af693cc7f33ab0487e021b4d44be44515e17afabd82ca1b43472d9550befd33e5b76c06f12afaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4a3c1b04188bf75935a19a5985.txt)

**Comment by zebdelk** [comment]
I saved the file and it passed the metadata parser. If there's an error, it must be on the rest request side of things. Going to try that next.

**Comment by zebdelk** [comment]
I was able to upload this file to our endpoint without an error, and see it in the staging_granule index.

If there has been a bugfix to uploading in the 2.1 release that would impact this, I'm not aware of it off the top of my head.

**Comment by dneufeldcu** [comment]
Could not reproduce, possibly environment specific to our partner.
