### ISSUE TITLE
Documentation Updates: Paleo time filtering follow-up

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#857]
Background:
We asked the paleo group to interact with the API/UI and read the updated wiki docs, and provide feedback. Now it's time to address their findings. See: https://docs.google.com/document/d/1Ek1qOk4ekNKjwFZoiyEZH2KpHy9y0u5wc-37Fqe15fY

Tasks:
  - [x] Current Era --> Common Era
      - [x] make sure this is clear in the docs
  - [x] In-depth explanations of how the relations work for time/spatial filters (migrate existing diagrams to digital format for time?)
  - [ ] Char escape in query
  - [ ] Start > End accepted (and returning results) in API
  - [ ] 404 bug -- not a bug (genuinely not an endpoint) -- but should we have a high-level endpoint? 
  - [ ] review doc for other issues that need to be addressed

Story Owner:
@ajakz

**Comment by ajakz** [comment]
We need to make sure we addressed everything in this doc from the paleo group. Probably all taken care so should be straightforward
