### ISSUE TITLE
fileIdentifier error message handling

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#861]
**As a** UAF user
**I want to be able to** migrate from geoportal to OneStop (before PSI capabilities)
**So that I can** decommission legacy system (and there will be much rejoicing in the land)

### ISSUE TO ADDRESS:
One issue to address is when **both** fileId and doi are null/empty (don't allow this)

Ambiguous metadata records in existence; metadata not loaded.

Metadata team has detected an error condition that they don't understand when uploading the linked metadata record.

Review code and make changes to better support this use case and more detail in the error generated.
[Metedata record](https://ferret.pmel.noaa.gov/uafwaf/iso/granule/psd_thredds_dodsC_Datasets_snowcover_snowcover.xml)

Specifically, the error message ```{"errors":[{"status":409,"title":"Ambiguous metadata records in existence; metadata not loaded.","detail":"Please GET records with ids [ (list of 10 ids) ] and DELETE any erroneous records. Ambiguity because of fileIdentifier [  ] and/or DOI [ null ]."}]}"```

This suggests that the file id and/or doi is not being parsed correctly for some reason,  and then the `findMetadata` function is going to do a query with `should: []` (i.e. no actual search criteria) which will just return the first 10 documents in the index.

Test that the file id and doi are rejected with an appropriate error message when this is the case.

```
   * Load three metadata records:
   * 1) fileId: A, doi: null --> creates ES Doc 1
   * 2) fileId: B, doi: null --> creates ES Doc 2
   * 3) fileId: A, doi: X    --> updates doi on ES Doc 1
   * Now, if we load a fourth document with fileId B and doi X, it is impossible to
   * determine if we're supposed to update ES Doc 1 or 2, so an error should be thrown
   * 4) fileId: B, doi: X    --> ERROR
```

**Comment by StrayCat1** [comment]
Current integration test around this behavior- 
https://github.com/cedardevs/onestop/blob/master/api-metadata/src/integrationTest/groovy/org/cedar/onestop/api/metadata/LoadIntegrationTests.groovy#L104
