### ISSUE TITLE
Simple Common Access Integration.

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#863]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a data center</td>
  </tr>
  <tr>
    <td><b>I want</b></td>
    <td>OneStop to be compatible with existing systems like Common Access</td>
  </tr>
  <tr>
    <td><b>So that</b></td>
    <td>my data center ingest, discovery and extract systems work end-to-end</td>
  </tr>
</table>

### Description
Demonstrate Common Access Integration in OneStop using the following sample metadata record. Provide feedback to metadata team based on UI links.

### Tasks
- [x] Add the following metadata record to our test data package on sciapps 
- [x] Confirm common access links are visible on collection record

[C01501.xml.txt](https://github.com/cedardevs/onestop/files/3080588/C01501.xml.txt)

**Comment by StrayCat1** [comment]
```
$ ./upload/uploadToOnestopApi.sh ~/Projects/CEDARDEVS/testData/ https://sciapps.colorado.edu/onestop/api/metadata
===========================================
Uploading files to https://sciapps.colorado.edu/onestop/api/metadata
===========================================
2019-05-01T14:47:23Z [1] SUCCESS -> /Users/chris/Projects/CEDARDEVS/testData//C01501.xml
===========================================
UPLOAD SUCCESS  : Uploaded all 1 XML files.
INDEXING FAILED : Could not update search index
```

**Comment by StrayCat1** [comment]
from client logs
>10.233.73.192 - - [01/May/2019:14:47:09 +0000] "POST /onestop/api/metadata HTTP/1.1" 404 218
128.138.136.103 - - [01/May/2019:14:47:10 +0000] "GET / HTTP/1.1" 200 45
10.233.73.192 - - [01/May/2019:14:47:10 +0000] "GET /onestop/api/admin/index/search/update HTTP/1.1" 404 235

from api-metadata (admin) logs- 
>2019-05-01 14:54:43.827  INFO 1 --- [   scheduling-1] o.c.o.api.metadata.service.ETLService    : Starting search indices update process
2019-05-01 14:54:44.867  INFO 1 --- [   scheduling-1] o.c.o.api.metadata.service.ETLService    : Reindexed 0 of 0 requested collections and 0 of 0 requested granules in 1.039s

**Comment by StrayCat1** [comment]
Example has been loaded to OneStop on sciapps
https://sciapps.colorado.edu/onestop/collections/details/e55418b1-9d7b-4f45-930b-9d07900e5f25?q=ABI

In PSI
https://sciapps.colorado.edu/registry/metadata/collection/e55418b1-9d7b-4f45-930b-9d07900e5f25

Updated tar with test data
https://github.com/cedardevs/onestop/commit/ccf385cbaf1ca5aacc9b2eaa92bde13b0876e8fa

**Comment by dneufeldcu** [comment]
Switch text from 'Search Data' to 'Search for Data' in access tab description.

**Comment by StrayCat1** [comment]
Okay, going beyond 'simple integration' into code changes- 
https://github.com/cedardevs/onestop/pull/898

**Comment by StrayCat1** [comment]
branch was merged
