### ISSUE TITLE
Media Current updated accessibility statement

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#882]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       demonstrate WCAG compliance
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>can comply with the Section 508 rules.</td>
  </tr>
</table>

### Description
On the about page for OneStop update the accessibility statement to something like "We have completed a 3rd party review that the site is Level AA accessibility for all of our features. We will continue to make improvements across our entire site aiming for AAA compliance where possible."

### Tasks
- [ ] Request review and updated statement from MediaCurrent.
  - Note: finish the other AA level 508 stories first

**Comment by StrayCat1** [comment]
Do we still need to run all the other 508 updates passed MediaCurrent before we merge this?
