### ISSUE TITLE
Spike - experiment with upgrading index from ES 5 to 6

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#889]
### Summary
<table>
  <tr>
    <td><b>As</b></td>
    <td>devops</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       migrate from ES 5 to 6
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>assist when the production environment is upgraded</td>
  </tr>
</table>

In dev, we usually just delete our ES indices and repopulate them when we make changes. However, in production, we'll want to preserve the existing data. In theory, ES has provided the mechanism to smoothly upgrade from ES 5 to 6. We just want to verify that we know how to do it, and that there are no serious gotchas for us.

- [x] use Elastic provided mechanism to upgrade ES versions
- [x] report out on if there are any concerns or difficulties that we should be aware of

**Comment by StrayCat1** [comment]
Our indices migrate smoothly from ES5 to ES6 without any special reindexing. 

Kibana indices need a special, one-off re-indexing.
