### ISSUE TITLE
Onestop search fails depending on landing page entry

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#891]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       ensure OneStop works even if an external link references the initial page incorrectly
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>confident that strange errors aren't reported by users when the link uses an unexpected format</td>
  </tr>
</table>

### Description
If you enter OneStop or if a link is used to reference OneStop incorrectly it results in unexpected search errors. For example, goto https://sciapps.colorado.edu/onestop/index.html and enter a search term. The error appears to result from assumptions in the rewrite rule.

### Tasks
- [ ] Modify javascript routing and/or rewrite rules in web server config to ensure search functions irrespective of initial entry.

**Comment by StrayCat1** [comment]
Reviewed, found some edge cases, implemented a fix with Elliott's help. 

Ready to merge pending Elliott's approval.
