### ISSUE TITLE
Promote Script errors

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#896]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>developer</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       run the promote script (for a hotfix)
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>consistently tag releases</td>
  </tr>
</table>

Two version updates that the promote script failed to correctly change:
- [x] skaffold.yaml
  - assuming there's a bug in the regex
- [x] helm/*/values.yaml
  - we changed these to 2.1-SNAPSHOT, which is still accurate on the 2.x release branch, but the promote script cannot handle right now

Additionally:
- [ ] The promote script should fail early if there's a problem
- [ ] The promote script should be clearer when using for hotfixes

**Comment by zebdelk** [comment]
One thing about the promote script (and how we handle versions in general) is that we do not change the version to M.m.p-SNAPSHOT after tagging a release. For example, just after tagging the 2.1.0 release, the version in master is 2.2.0. The intent in that decision was to prevent us from accidentally using a version that had already been tagged, but in practice it's more confusing and would probably be clearer if it specifically had -SNAPSHOT in the version.

**Comment by StrayCat1** [comment]
The team decided that we would rather have the promote script not handle `git` commands. 

The promote.sh script is being deprecated in favor of a script called manageVersions.sh. The main difference between the two is that the latter does not handle any git commands and adds an additional utility function to GET the version in each file before and after SETing the version. 

The docs have been updated to account for the difference.
