### ISSUE TITLE
First pass aggregated view

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#9]
Begin a dashboard for aggregated view.  Review slide 5 wireframe in balsamiq [https://hangouts.google.com/hangouts/_/noaa.gov/sprint-planning?authuser=0]

Use facets initially for comparison across collections.

AC: Select 2 collections and go to aggregated view screen; see pie charts of facet counts

**Comment by aaronjcaldwell** [comment]
Has dependency on #10

**Comment by dneufeldcu** [comment]
Let this one re-emerge if needed.
