### ISSUE TITLE
Troubleshoot error message for UAF metadata

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#903]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>metadata loader</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
      understand why I'm getting 400 errors after loading metadata records
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>feel confident my metadata has loaded properly</td>
  </tr>
</table>

## Tasks
- [ ] Review error messages and metadata files associated with UAF metadata uploads to production

**Comment by dneufeldcu** [comment]
Logs and metadata sent via email.

**Comment by StrayCat1** [comment]
The bug as I understand it-  
1) they tried to load UAF granules from this WAF https://ferret.pmel.noaa.gov/uafwaf/iso/granule/
```
UPLOAD=https://hubcap.ncdc.noaa.gov/onestop/api/metadata/
curl -n -sS $UPLOAD -H "Content-Type: application/xml" -d "@$file"
```
2) they received responses that contained 400s but did not contain error details, and contained parsed data as if all was successful. The response ends with -
```
"meta":{"filename":null,"status":400,"created":null}
```
3) they tried to trigger an ETL -  
```
UPDATE=https://hubcap.ncdc.noaa.gov/onestop/api/admin/index/search/update
curl -n -sS $UPDATE
```
and received - 
```
Wed May 29 12:25:07 EDT 2019 - Triggering search index update: {"errors":[{"id":null,"status":400,"title":"No identifiers provided with request","detail":"Provide a fileId and/or doi request parameter"}]}
```

**Comment by StrayCat1** [comment]
@dneufeldcu what is the status on this? You sent an email to Li and Nico saying "the record appears to be loading into the staging index", and "we have at least some records loaded without identifiers in staging". While that is what the errors provided seem to indicate, I want to make sure that is accurate. Did we confirm by actually looking for those granules in staging? 

Also, Nico forwarded me an email from you and Anna where you identified that a collection had a trailing space and that was the reason for the error. Was that the same UAF issue? Did those granules ever make it to search?

Should I be trying to re-create this so we can adjust the errors?

**Comment by dneufeldcu** [comment]
No not confirmed about record making it to staging. Maybe we close and revisit the issue after version 2.1 has been deployed?

**Comment by StrayCat1** [comment]
Closing this in hopes the issue will not exist or be easier to handle in version 2.1
