### ISSUE TITLE
Allow kafka triggered delete 

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#911]
When a record is deleted from PSI, we add a tombstone to that record. When OneStop receives that tombstone, we want to remove that record from all indices. 

Need more details about what that message will look like coming from PSI.

**Comment by dneufeldcu** [comment]
Duplicate see: https://app.zenhub.com/workspaces/onestop-5caf5b03e94905314d5883a8/issues/cedardevs/onestop/976
