### ISSUE TITLE
Make Loading More Visible + "No results" bug

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#922]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>User</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       See the loading indicator
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>tell what's going on when loading happens</td>
  </tr>
</table>
Edit: it used to say "Loading" instead of "No results" when the request was in flight. Step one is fixing that. 

For the granule link on the collection detail page, the granule count request can be in a different state than the main GET request, and shouldn't interfere with showing the actual details
- [ ] if that request errors - where / how to show it?
- [ ] if that request is loading after the GET completes, there should be a separate loading indicator in just the Files panel (may require decoupling the inFlight status / loading check logic for the two requests a little more)
- [ ] if that request errors / takes too long to complete, the show granules link with NO filters applied should always be made available, even if it wouldn't show otherwise
- [ ] that part of the UI should rely on the appropriate inFlight check (currently named backgroundInFlight, but likely to get renamed between then an now) and NOT on the filteredGranuleCount value (the collectionDetailRequest reducer should stop resetting that value when a new request starts)

More general loading things to update:
- [ ] make styling for loading more visible overall - the loading bar is so small it's sometimes hard to see (check prod for examples that load slower) so that we don't have to put the word "loading" in our headers, hopefully (keep an eye on 508 needs if we do change this)
- [ ] put a loading indicator on the show more button, since all the loading indicators are off screen when a user clicks that

**Comment by StrayCat1** [comment]
![image](https://user-images.githubusercontent.com/26884996/70277120-f73c7f80-176e-11ea-9164-2d0798675540.png)

and while granules are loading before the detailed collection view- 
![image](https://user-images.githubusercontent.com/26884996/70280596-02df7480-1776-11ea-97c4-c8e9a154a759.png)

looks good!

And the errors look decent too! 
when the detail request fails- 
![image](https://user-images.githubusercontent.com/26884996/70282207-708d9f80-177a-11ea-83f6-2327360f7980.png)

when the granule list request fails- 
![image](https://user-images.githubusercontent.com/26884996/70282229-800ce880-177a-11ea-96e7-072c288d4bd1.png)
