### ISSUE TITLE
Granule filtering map weirdness

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#923]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>person using granule geometry filtering</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       see my filters applied on the map
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>tell what's going on</td>
  </tr>
</table>

- [x] the existing filter isn't shown on the granule filter map / disappears when you draw even though the filter is applied successfully
  - it sometimes seems to display successfully when I reload the page with the filter applied
- [x] (possibly related) the same behavior on the collection filter is working, but seems to change the color of the map selection somewhat randomly?

A somewhat related bug re geometry:
- [x] entering coordinates with the text boxes: W: -160, S: 0, E: -150, N: 25 is marked as "invalid" even though it shouldn't be. Probably a zero vs null truthiness check?

**Comment by StrayCat1** [comment]
Notes and observations: 
- collection location filter applies to granules, and is visible from the granule list view when the map is open, but you can't clear the box. You can clear the filter input and that unfilters the results, but the box stays visible on the map. Notice in the image below that the location filter is clear but the box remains. 
![Screen Shot 2019-07-30 at 9.06.08 AM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/8f61a613-3738-42c7-8226-0bce2b634150)
