### ISSUE TITLE
Granule request on details page enhancements

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#925]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
<td>dev</td>
    <td>user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       not send unneeded requests
    </td>
<td> see granule filters tied to the show granules link </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>have efficient use of resources</td>
<td>see what the link will do</td>
  </tr>
</table>

- [x] the granule count request associated with the collection details page will have no impact whatsoever if there are no filters applied. For performance reasons, we should skip sending it in that case.
  - [x] relatedly, the actual search pages verify that the filters do not match what is already in the redux store before sending off requests, and we should double check that the details page also does so, if it's actually needed
- [x] DISCUSS: is there a good (concise) way to display the Show Granules link that indicates the filters that will be applied to the search (or at minimum, the number of filters?)

**Comment by StrayCat1** [comment]
@zebdelk Seeking feedback here. 

I think we are talking about this call to get the granule count- 
https://github.com/cedardevs/onestop/blob/aac6abc9b656c156949e35e4b786bfd4a6311c3d/client/src/actions/routing/CollectionDetailRouteActions.js#L73

If so, I am to check for empty filters like so- 
https://github.com/cedardevs/onestop/commit/5fe756e47b3e31f69ac351677551f619c63b1658

But when I comment out 'dispatch(granuleMatchingCountRequested())` completely, I cant really tell a difference. The granule count seems accurate either way.

**Comment by StrayCat1** [comment]
>relatedly, the actual search pages verify that the filters do not match what is already in the redux store before sending off requests, and we should double check that the details page also does so, if it's actually needed


We do check when we load details from the url- 
https://github.com/cedardevs/onestop/blob/aac6abc9b656c156949e35e4b786bfd4a6311c3d/client/src/actions/InitActions.js#L27
which is ultimately called here anytime the route is changed to a detail page
https://github.com/cedardevs/onestop/blob/aac6abc9b656c156949e35e4b786bfd4a6311c3d/client/src/init.js#L18 
https://github.com/cedardevs/onestop/blob/aac6abc9b656c156949e35e4b786bfd4a6311c3d/client/src/init.js#L37

**Comment by StrayCat1** [comment]
>DISCUSS: is there a good (concise) way to display the Show Granules link that indicates the filters that will be applied to the search (or at minimum, the number of filters?)

This is what it looks like now - 
![Screen Shot 2019-08-02 at 2.06.09 PM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/3e00948b-4a18-4fc8-a49f-0c7803b3af36)
