### ISSUE TITLE
Re-keying Strategy

### ISSUE THREAD

**Issue by forgo** [cedardevs/onestop#927]
**On Startup:**

1. add these fields to staging mapping:
    - `previousInternalId` field (represents old ES-generated ID)
    - `fromKafka` bool field (demarcates staging items which came from Inv. Mgr)

**Kafka Ingest:**

1. if previous ES-generated ID exists, set `previousInternalId`
2. set `fromKafka` to `true`

**On ETL** (note: if collection w/ `previousInternalId` changed later, these first two steps are no-op and safe):

1. delete from search by `previousInternalId`
2. if collection, update `internalParentId` on  the collection's un-flattened search granules
3. ETL as normal
    - Note: if "ETL as normal" for a collection includes updating its un-flattened search granules as well, then step 2 is not needed

**API:**

1. add endpoint `/needsRekey` for what hasn't been keyed to Inv. Mgr. (this is items in staging that have no previousInternalId AND are not fromKafka)
2. add tests for this migration pattern

**Long-term Considerations** (once ETL responsibilities are handled by PSI and PSI can correlate granules):
- can we automate the deletion of staging once the `/needsRekey` endpoint returns an empty list?
- and/or can we delete individual records out of staging once we know that there are in kafka?

**Comment by dneufeldcu** [comment]
No longer necessary reload from scratch.
