### ISSUE TITLE
HIP: fix version number throughout build

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#936]
SNAPSHOT is added dynamically based on when something is built, and it causes confusion.

- [x] remove SNAPSHOT logic from gradle publish script
- [ ] ~update promote script to add -SNAPSHOT in `gradle.properties` at the correct time~
- [ ] ~document that the version on the release/2.x branch should never have -SNAPSHOT in it (to prevent prod builds from saying the wrong version)~
- [x] update circle script to push a tagged docker image for version tags (currently it only pushes up -SNAPSHOT images)
- [ ] ~update promote script to handle hotfixes more gracefully OR create a separate hotfix script~

**Comment by StrayCat1** [comment]
This is duplicate with #944 and #896

What we did- 
Promote.sh script is now manageVersions.sh and all it does it update version numbers. It no longer runs git commands. Git commands and steps documented further.
