### ISSUE TITLE
Remove "Access Protocols" from granules search result page 

### ISSUE THREAD

**Issue by Ghebrechristos** [cedardevs/onestop#947]
The access protocols at the top of the list are redundant because each access link in the granule view has the protocol icon.  For example-   ![Screen Shot 2019-07-29 at 4.20.51 PM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/fdd1fc24-1f0a-4494-80e4-0b8e6e1a00a2)

Do we want to keep "Access Protocols" at the top? NO!

After team discussion:
We don't want to keep the whole legend front and center and think that tooltips are a good alternative.

**Comment by amilan17** [comment]
may I get clarification on what this issue means? (Thanks!)

**Comment by StrayCat1** [comment]
I believe this issue arose when someone noticed that we have "access protocols" at the top of the granule list results and also in each list item, which seems redundant. 

Before we work on this, we should confirm with the team, stakeholders, and users that this change is desirable. 

@amilan17 do you have an opinion?

**Comment by amilan17** [comment]
I think it's redundant and unnecessary.
Thanks for checking in.
Anna

**Comment by StrayCat1** [comment]
Also noticed that when there are not results 'Access Protocols' still shows. 
![Screen Shot 2019-08-13 at 12.00.03 PM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/e96712c9-0b0d-48b4-9847-b6ad564c314d)

**Comment by dneufeldcu** [comment]
Move legend away from top and move to a hover over tooltip in results
