### ISSUE TITLE
Service Links on granules

### ISSUE THREAD

**Issue by zebdelk** [cedardevs/onestop#948]
- [x] Add a section (closed by default) to show service links for granules (if present)
- [ ] Test with UAF metadata record(s)

**Comment by StrayCat1** [comment]
This is a first pass using the granule view we have now, which is pretty small. In fact, it is too small to display each service title and the links under it. So instead we just listed the links without the service title. 

If we hear back from the metadata team or whoever that we need to show each service title and the links under it like we do for collections, we will have to start discussing an expanded granule view. 
![Screen Shot 2019-07-23 at 3.05.40 PM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/a2dc76e3-c1b4-4659-93b8-cd0a97b1bcbf)
