### ISSUE TITLE
Configure google analytics on data.noaa.gov 

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#957]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>Project manager</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       understand user demographics of people visiting my web site
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>develop a deeper understanding of who my users are</td>
  </tr>
</table>

## Tasks
- [ ] Update search-api configuration to reference OneStop google analytics using 'UA-108560292-1'
- [ ] Confirm implementation with DeeDee Anders

**Comment by dneufeldcu** [comment]
Configured but not working. Created new story #969

**Comment by ajakz** [comment]
Closing this as complete, since #969 seems to override this and was closed by Zeb.
