### ISSUE TITLE
Clean up the OneStop backlog

### ISSUE THREAD

**Issue by StrayCat1** [cedardevs/onestop#963]
Our new issue column is getting out of hand. 

- [ ] associate stories with epics
- [ ] epics go in the epic column in order of priority
- [ ] delete duplicates
- [ ] groom granule filtering stories
- [ ] update epics and stories to accurately reflect the progress of each epic

**Comment by dneufeldcu** [comment]
Chris let's work together on this one.

**Comment by StrayCat1** [comment]
Associated some stories with epics, added clarity to some, removed duplicates. This is a never ending process, obviously. Calling it good for now.
