### ISSUE TITLE
Revisit Google Analytics

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#969]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>analytics consumber</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       track usage of the production site.
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>inform my managers about how many people are using the site</td>
  </tr>
</table>

## Description
The feature toggle for google analytics has been turned on in the test, but the correct UA is not being sent to google.

Review:
https://data.test.ncei.noaa.gov/onestop/

Note:
UI Config correctly returns UA
"googleAnalytics":{"profiles":[{"trackingId":"UA-108560292-1"}]

However the outbound request contains:
tid=UA-33523145-1

coming from:
https://data.test.ncei.noaa.gov/scripts/federated-analytics.js?agency=DOC%26subagency=NOAA

Perhaps we need to name the trackingID in react-ga and call it explicitly to override the default being set above?
https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#named

AC: React-GA sends tracking information for both DOC UA-id and NCEI (or Cedar-CIRES) UA-id
tid=UA-33523145-1

**Comment by StrayCat1** [comment]
We dont use the analytics script anymore. 

https://data.test.ncei.noaa.gov/scripts/federated-analytics.js?agency=DOC%26subagency=NOAA

i.e. this is not in the client repo- federated-analytics.js

But I can take some time to set up analytics on sciapps (if it isnt already) so we can use that to confirm it is working as expected.

**Comment by dneufeldcu** [comment]
Chris we may want to discuss this a bit more so you have the full context. Also can you access https://data.test.ncei.noaa.gov/onestop ?

federated-analytics is still in use via a server-side include on the federal systems to inject a mandated DOC tracking ID. I believe this is causing a collision. There may be other non-software approaches to solving this issue though.

**Comment by StrayCat1** [comment]
Thanks @dneufeldcu for the clarification.  I am available to chat about it at your convenience if you want to call me up on a hangout or something. 

Anyway, all I mean is that this- 
>UI Config correctly returns UA
"googleAnalytics":{"profiles":[{"trackingId":"UA-108560292-1"}]

Is irrelevant to what their script sends. If it is their script sending the wrong tracking Id, they need to update their script. 

I can't reach that data.test.ncei.noaa.gov url from my CU machine, but haven't booted up my fed machine to see if I can get it from there. I want to say I can, pretty sure I have before.

**Comment by StrayCat1** [comment]
I have confirmed that the federated-analytics script can be used in conjunction with the react components. 
When the configuration for the react component includes 2 profiles/trackingIds, e.g.
```
- trackingId: 'UA-127993388-1'
  gaOptions:
    name: cedardevs
- trackingId: 'UA-145187287-1'
  gaOptions:
    name: chris
```
AND the federated-analytics.js script runs, using the analytics debugger tool you can see all three trackers get created and events sent to them - 
![Screen Shot 2019-08-07 at 12.48.50 PM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/4e154273-d236-4939-829a-0e066d41d7ff)

When one of the trackers is unnamed, e.g. - 
```
- trackingId: 'UA-127993388-1'
- trackingId: 'UA-145187287-1'
  gaOptions:
    name: chris
```
The unnamed tracker is considered the default tracker. This configuration also works with federated-analytics.js. You can see in the logs below how the first tracker goes unnamed. The advantage of this configuration is that you can disable that default tracker with `googleAnalytics.reactGaOptions.alwaysSendToDefaultTracker: false`. That param will not effect the federated-analytics.js. You can also see in the logs that the federated analytics tracker names its tracker, thus it is not considered a default tracker and should not conflict with our app's default tracker. 

![Screen Shot 2019-08-07 at 12.51.46 PM.png](https://images.zenhubusercontent.com/5caf61bfe94905314d588424/4aad0764-62d8-4e02-aef6-8e87f8a3af85)

I recommend that our federal partners use both, their script and our react components. If you run the google analytics debugger, you can see that their script sends additional things that ours does not and vice versa.
