### ISSUE TITLE
Consistent display of browseGraphics

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop#995]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>user</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       to see browseGraphics in their original aspect ratio
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>see a non-stretched cleaner browse graphic on the granule view</td>
  </tr>
</table>

### Tasks
- [ ] Fix the browse graphic display on granule view so images are not stretched.

### Reference
https://data.noaa.gov/onestop/collections/granules/AWb1V6bwYJ6J3EnSGzPx

**Comment by zebdelk** [comment]
fixed by PR#1016
